-- Live synthetic cases are enclosed in a transaction and leave no retained rows.
begin;
do $$
declare u uuid:=gen_random_uuid();u2 uuid:=gen_random_uuid();p uuid;p2 uuid;s jsonb;r jsonb;a jsonb;items jsonb;t uuid;before_count integer;rev integer;request uuid:=gen_random_uuid();denied boolean;moment uuid;concept uuid;help_version uuid;canonical_label text;canonical_definition text;
begin
 insert into auth.users(id,aud,role,email) values(u,'authenticated','authenticated','core-'||u||'@example.invalid'),(u2,'authenticated','authenticated','core-'||u2||'@example.invalid');
 insert into gf_core.persons(auth_user_id) values(u) returning person_id into p;
 insert into gf_core.persons(auth_user_id) values(u2) returning person_id into p2;
 insert into gf_core.privacy_preferences(person_id,memory_allowed) values(p,true),(p2,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 s:=public.lumen_s1_accompany_moment('Estoy agotada del trabajo y quiero estar más presente con mis hijos.','es-AR','es','web',gen_random_uuid(),true);
 assert s->>'scene_id'='moment.understanding';moment:=(s->>'moment_id')::uuid;
 assert s->'interpretation'->'area_keys' @> '["work","wellbeing","family_care"]'::jsonb;
 assert not exists(select 1 from gf_core.decision_runs where episode_id=(s->>'episode_id')::uuid);
 assert not exists(select 1 from gf_core.candidate_exposures where person_id=p);
 r:=public.lumen_s1_review_moment((s->>'episode_id')::uuid,'Quiero cuidar mi descanso.','{wellbeing}',5);
 assert r->>'state'='reviewed';assert (select area_keys=array['wellbeing'] from gf_core.moment_interpretations where moment_id=moment);
 assert (select expression_text='Estoy agotada del trabajo y quiero estar más presente con mis hijos.' from gf_private.moment_originals where moment_id=moment);
 a:=public.lumen_faro_potential_proposal('Estoy agotada y quiero estar más presente con mis hijos.','Estar presente con mis hijos');
 assert jsonb_array_length(a->'items')>0;assert a->'items'->0->>'origin'='lumi';assert a->'items'->0->>'concept_id' is null;
 assert a->'items'->0->>'status'='proposed';assert a->'items'->0->>'contextual_meaning'<>'';assert a->'items'->0->>'reason'<>'';
 a:=public.lumen_faro_potential_proposal('Estoy agotada','Aprender a pintar');assert a->'items'->0->>'label'='Aprender con curiosidad';
 a:=public.lumen_faro_potential_proposal('Estoy agotada','No quiero aprender. Quiero cuidar mis vínculos.');assert not exists(select 1 from jsonb_array_elements(a->'items') i where i->>'label'='Aprender con curiosidad');
 a:=public.lumen_faro_potential_proposal('quiero morir','quiero morir');assert a->>'state'='safety_referral';assert a->'items'='[]'::jsonb;
 items:=jsonb_build_array(jsonb_build_object('identity_id',gen_random_uuid(),'concept_id',null,'label','Escuchar con cuidado','definition','Dar atención a lo que importa','contextual_meaning','Escuchar a mis hijos sin apuro','origin','lumi','status','accepted'));
 select count(*) into before_count from gf_core.trajectories where person_id=p;
 denied:=false;begin perform public.lumen_faro_review_confirm(null,'Cuidar mi presencia',jsonb_set(items,'{0,label}','""'),'{}',0,null,moment,'active');exception when check_violation then denied:=true;end;
 assert denied;assert (select count(*)=before_count from gf_core.trajectories where person_id=p);
 a:=public.lumen_faro_review_confirm(null,'Cuidar mi presencia',items,'{family_care}',0,null,moment,'active',null,null,request);t:=(a->>'trajectory_id')::uuid;
 r:=public.lumen_faro_review_confirm(null,'Cuidar mi presencia',items,'{family_care}',0,null,moment,'active',null,null,request);assert (r->>'trajectory_id')::uuid=t;assert (r->'agreement'->>'version')::int=1;
 assert a->'agreement'->>'state'='validated';assert a->'agreement'->'items'->0->>'origin'='lumi';rev:=(a->'agreement'->>'faro_revision')::int;
 assert (select cardinality(capability_keys)=0 from gf_core.trajectories where trajectory_id=t);
 assert a->'agreement'->>'original_expression'='Estoy agotada del trabajo y quiero estar más presente con mis hijos.';
 denied:=false;begin perform public.lumen_faro_review_confirm(t,'Otro Faro',items,'{}',0,rev,moment,'active');exception when serialization_failure then denied:=true;end;
 assert denied;assert (select faro_text='Cuidar mi presencia' from gf_core.trajectories where trajectory_id=t);
 denied:=false;begin perform public.lumen_faro_review_confirm(t,'Otro Faro',jsonb_set(items,'{0,label}','""'),'{}',1,rev,moment,'active');exception when check_violation then denied:=true;end;
 assert denied;assert (select faro_text='Cuidar mi presencia' and revision=rev from gf_core.trajectories where trajectory_id=t);
 -- A reviewed-link fixture is visible only inside this rollback transaction. This is not editorial admission.
 select c.concept_id,l.help_version_id,c.label_es,c.definition_es into concept,help_version,canonical_label,canonical_definition from gf_core.help_potential_links l join gf_core.potential_concepts c on c.concept_id=l.concept_id join gf_core.help_versions hv on hv.help_version_id=l.help_version_id join gf_core.help_possibilities hp on hp.help_id=hv.help_id and hp.current_version=hv.version where hp.lifecycle in('active','active_limited') limit 1;
 assert concept is not null;
 update gf_core.potential_concepts set editorial_status='reviewed' where concept_id=concept;
 update gf_core.help_potential_links set editorial_status='reviewed' where concept_id=concept and help_version_id=help_version;
 items:=jsonb_build_array(jsonb_build_object('identity_id',gen_random_uuid(),'concept_id',concept,'label',canonical_label,'definition',canonical_definition,'contextual_meaning','Explorar esto en mi Faro','origin','lumi','status','accepted'));
 a:=public.lumen_faro_review_confirm(t,'Cuidar mi presencia',items,'{family_care}',1,rev,null,'active');
 r:=public.lumen_faro_constellation(t,2,0,'es-AR');assert r->>'state'='success';assert jsonb_array_length(r->'items')>0;
 items:=jsonb_set(items,'{0,status}','"withdrawn"');
 a:=public.lumen_faro_agreement_validate(t,'Cuidar mi presencia',items,'{family_care}',2);
 r:=public.lumen_faro_constellation(t,3,0,'es-AR');assert r->>'state'='no_match';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u2,'role','authenticated')::text,true);
 denied:=false;begin perform public.lumen_s1_review_moment((s->>'episode_id')::uuid,'Quiero descansar','{}',5);exception when insufficient_privilege then denied:=true;end;assert denied;
 denied:=false;begin perform public.lumen_faro_review_confirm(t,'Invadir Faro',items,'{}',1,rev,null,'active');exception when sqlstate 'P0002' then denied:=true;end;assert denied;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 update gf_core.privacy_preferences set memory_allowed=false where person_id=p;
 denied:=false;begin perform public.lumen_faro_review_confirm(null,'Sin consentimiento',items,'{}',0,null,null,'active');exception when insufficient_privilege then denied:=true;end;assert denied;
 assert not has_function_privilege('anon','public.lumen_faro_review_confirm(uuid,text,jsonb,text[],integer,integer,uuid,text,uuid,text,uuid)','execute');
 assert not has_function_privilege('anon','public.lumen_s1_review_moment(uuid,text,text[],integer)','execute');
end $$;
select 'PASS: review before generation, multi-area, original, reformulated hypotheses, negation, safety, atomic rollback, stale agreement, ownership, consent and ACL' as result;
rollback;
