import {test,expect} from './fixtures'
const label='LUMI: opciones y ayuda de este espacio'
test('Attached master: host is present in every root, scene, loading and error state',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.route('**/rest/v1/rpc/**',r=>r.fulfill({json:r.request().url().endsWith('lumen_source_discover')?[]:{areas:[]}}))
 for(const route of ['/','/mi-vida','/explorar','/tejido','/santuario','/mi-vida/faro','/aprender','/ajustes','/vivir/missing']){
  await page.goto(route);const orb=page.getByRole('button',{name:label});await expect(orb).toBeVisible();await expect(orb).toHaveCount(1);await expect(page.getByRole('dialog')).toHaveCount(0);await orb.click();const sheet=page.getByRole('dialog');await expect(sheet).toBeVisible();await expect(sheet.getByText('Cómo funciona este espacio',{exact:true})).toBeVisible();await expect(sheet.locator('video,iframe')).toHaveCount(0);await sheet.getByText('Leer la transcripción',{exact:true}).click();await expect(sheet.locator('details')).toHaveAttribute('open','');await expect(sheet.getByRole('button',{name:/^(Fuente|Santuario|Tejido|Mi Vida|Explorar)$/})).toHaveCount(0);await page.keyboard.press('Escape');await expect(sheet).toHaveCount(0);await expect(orb).toBeFocused();expect(await orb.evaluate(el=>getComputedStyle(el.firstElementChild!).animationName)).toBe('none');
 }
 await page.goto('/');const nav=page.locator('.gm-nav');const navBox=await nav.boundingBox();const viewport=page.viewportSize()!;expect(navBox!.y+navBox!.height).toBeLessThanOrEqual(viewport.height+1);if(viewport.width>=1024){expect(navBox!.width).toBeLessThanOrEqual(390)}await page.goto('/explorar');await page.getByRole('button',{name:label}).click();await page.getByRole('button',{name:'Hasta 5 min',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:label}).click();await expect(page.getByRole('button',{name:'Sin límite de tiempo'})).toBeVisible();await page.getByRole('button',{name:'Cerrar LUMI'}).click();await page.screenshot({path:`test-results/master-explore-${test.info().project.name}.png`,fullPage:true})
})
test('Attached master: invocation, transcript, quiet rhythm and no fabricated memory',async({page})=>{
 await page.goto('/');const orb=page.getByRole('button',{name:label});await orb.click();await page.screenshot({path:`test-results/master-lumi-sheet-${test.info().project.name}.png`,fullPage:true});await page.getByRole('button',{name:'Hablar con LUMI',exact:true}).click();await expect(page.getByText('No estoy usando recuerdos de sesiones anteriores.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Cerrar LUMI'}).click();await page.goto('/ajustes');await orb.click();await page.getByRole('button',{name:'Modo Quieto',exact:true}).click();await expect(orb).toHaveClass(/is-quiet/);await page.reload();await expect(orb).toHaveClass(/is-quiet/);await orb.click();await expect(page.getByRole('button',{name:'Volver a una presencia suave'})).toBeVisible();await expect(page.getByRole('button',{name:/ocultar|desactivar LUMI|sin LUMI/i})).toHaveCount(0)
})
test('Attached master: chosen atmosphere survives reload independently of system theme',async({page})=>{
 await page.emulateMedia({colorScheme:'light'});await page.goto('/ajustes');await page.getByLabel('Atmósfera',{exact:true}).selectOption('dark');await expect(page.locator('.gm-settings')).toHaveCSS('background-color','rgb(31, 42, 36)');await page.reload();await expect(page.getByLabel('Atmósfera',{exact:true})).toHaveValue('dark');await expect(page.locator('.gm-settings')).toHaveCSS('background-color','rgb(31, 42, 36)');await page.getByLabel('Atmósfera',{exact:true}).selectOption('light');await page.emulateMedia({colorScheme:'dark'});await expect(page.locator('.gm-settings')).toHaveCSS('background-color','rgb(244, 238, 226)');await expect(page.getByRole('button',{name:label})).toBeVisible()
})
