import {editFaro} from './experience-actions'
import {test,expect} from './fixtures'

test.describe('LUMEN PREMIUM V58 · public doors',()=>{
 test.beforeEach(async({page})=>{await page.goto('/');await expect(page.getByRole('button',{name:'Cuenta',exact:true})).toBeEnabled({timeout:30000})})
 test('present Momento protects personal persistence behind identity',async({page})=>{
  await expect(page.getByRole('heading',{name:'¿Qué está pasando ahora?'})).toBeVisible()
  await page.getByLabel('¿Qué está vivo hoy?').fill('Quiero descansar y entender qué necesito hoy.')
  await page.getByRole('button',{name:'Continuar'}).click()
  await expect(page.getByRole('dialog',{name:'Entrar a LUMEN'})).toBeVisible()
 })
 test('five doors are distinct and Santuario is reachable',async({page})=>{
  for(const door of ['Inicio','Mi Vida','Explorar','Tejido','Santuario']) await expect(page.locator('.gm-nav').getByText(door,{exact:true})).toBeVisible()
  await expect(page.locator('.gm-nav button')).toHaveCount(5)
  await page.locator('.gm-nav').getByText('Santuario').click()
  await expect(page.getByRole('heading',{name:'Mi Santuario'})).toBeVisible()
  await page.getByRole('button',{name:'Entrar a mi Santuario'}).click()
  await expect(page.getByRole('dialog',{name:'Entrar a LUMEN'})).toBeVisible()
  await page.getByRole('button',{name:'Cerrar'}).click()
  await page.locator('.gm-nav').getByText('Mi Vida').click()
  await expect(page.getByRole('heading',{name:'Mi Vida',exact:true})).toBeVisible()
  await page.getByText('Mirar con más detalle').click()
  await page.getByRole('button',{name:'Potencial',exact:true}).click()
  await expect(page.getByRole('button',{name:'Potencial',exact:true})).toHaveClass(/on/)
  await page.locator('.gm-nav').getByText('Explorar').click()
  await expect(page.getByRole('heading',{name:'Explorar',exact:true})).toBeVisible()
  await page.locator('.gm-nav').getByText('Tejido').click()
  await expect(page.getByRole('heading',{name:'Tejido'})).toBeVisible()
 })
 test('Faro is editable and the contextual boundary is honest',async({page})=>{
  await page.locator('.gm-nav').getByText('Mi Vida').click()
  await page.getByRole('button',{name:'Elegir un Faro'}).click();await editFaro(page)
  await expect(page.getByRole('heading',{name:'Mi Faro'})).toBeVisible()
  if(await page.getByRole('button',{name:'Revisar y ajustar'}).isVisible())await page.getByRole('button',{name:'Revisar y ajustar'}).click()
  await page.getByLabel('Orientación de mi Faro').fill('Cuidar mi descanso')
  await page.getByRole('button',{name:'Guardar el Faro y seguir después'}).click()
  await expect(page.getByRole('dialog',{name:'Entrar a LUMEN'})).toBeVisible()
 })
 test('mobile has no horizontal overflow',async({page})=>{
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
 })
 test('Fuente exposes a real attributed audio rather than an empty first page',async({page})=>{
  await page.locator('.gm-nav').getByText('Explorar').click()
  await page.getByText('Filtros de esta búsqueda',{exact:true}).click()
  await page.getByRole('button',{name:'Audios',exact:true}).click()
  await expect(page.getByText('Poner los pies en la tierra · audio OPS/OMS',{exact:true})).toBeVisible({timeout:45000})
  await page.locator('.gm-context-card').filter({hasText:'Poner los pies en la tierra · audio OPS/OMS'}).getByRole('button',{name:'Conocer esta posibilidad'}).click()
  await expect(page.getByRole('heading',{name:'Poner los pies en la tierra · audio OPS/OMS'})).toBeVisible()
  await expect(page.locator('.gm-nav')).toBeVisible()
  await page.getByRole('button',{name:'Empezar',exact:true}).click()
  await expect(page.getByRole('link',{name:'Escuchar en OPS/OMS',exact:true})).toHaveAttribute('href',/paho\.org/)
 })
 test('Tejido offers a real human service with attribution',async({page})=>{
  await page.locator('.gm-nav').getByText('Tejido').click()
  await page.getByText('Necesito acompañamiento humano',{exact:true}).click()
  await expect(page.getByText('Orientación profesional en salud mental · Argentina',{exact:true})).toBeVisible({timeout:45000})
  await page.getByText('Orientación profesional en salud mental · Argentina',{exact:true}).click()
  await expect(page.getByRole('heading',{name:'Orientación profesional en salud mental · Argentina'})).toBeVisible()
 })
})

