import {useState} from 'react'
import {conserveComposition,setRecurringPractice,type CompositionReference,type RecurringPractice} from '../greenfield/application/cultivation'
import {getFaroAgreement} from '../greenfield/application/faro-agreement'
import {setConsent} from '../greenfield/application/consent'
import type {SanctuaryEntry} from '../greenfield/application/embryo'

export function CompositionKeeper({trajectoryId,entry,items,onSaved,onMemory,onExplore}:{trajectoryId:string;entry:SanctuaryEntry|null;items:CompositionReference[];onSaved:(id:string,restore:boolean)=>Promise<void>;onMemory:(action:()=>Promise<void>)=>void;onExplore:()=>void}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const save=async(restore:number|null=null)=>{setBusy(true);setError('');try{const a=await getFaroAgreement(trajectoryId);const result=await conserveComposition(trajectoryId,a.version,items,entry?.entry_id||null,entry?.composition?.version||0,restore);await onSaved(result.entry_id,restore!==null);setMessage(restore?'Recuperaste esa versión como una nueva. Las anteriores siguen conservadas.':'Conservaste la composición completa. Sus recursos no se convirtieron en propios.')}catch(e){setError(e instanceof Error?e.message:'No pudimos conservar la composición.')}finally{setBusy(false)}}
 return <section className="gm-composition" aria-label="Conservar mi composición"><h2>Algo que quiero conservar</h2><p>Tu Faro, ámbitos, potenciales y selección, con referencias a sus fuentes. Vos elegís cuándo guardar los cambios.</p>{entry?.composition&&<p>Composición conservada · versión {entry.composition.version}</p>}<button className="gm-secondary" disabled={busy} onClick={()=>onMemory(()=>save())}>{busy?'Conservando…':entry?'Conservar una nueva versión':'Conservar esta composición en Santuario'}</button><button className="gm-secondary" onClick={onExplore}>Enriquecer desde Explorar</button>{entry?.composition&&<details><summary>Versiones que conservé</summary>{entry.composition.versions.map(v=><article key={v.version}><h3>Versión {v.version}</h3><p>{v.agreement.faro_text} · {v.items.length} referencias conservadas</p><button disabled={busy} onClick={()=>onMemory(()=>save(v.version))}>Recuperar versión {v.version}</button></article>)}</details>}{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}</section>
}

export function RecurringChoice({helpId,trajectoryId,entryId,onChanged,onMemory}:{helpId:string;trajectoryId:string|null;entryId:string|null;onChanged:()=>Promise<void>;onMemory:(action:()=>Promise<void>)=>void}){
 const [accepted,setAccepted]=useState(false),[days,setDays]=useState(7),[time,setTime]=useState('09:00'),[conditions,setConditions]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const zone=Intl.DateTimeFormat().resolvedOptions().timeZone
 const save=async()=>{setBusy(true);setError('');try{if(!accepted)return;await setConsent('proactivity',true,'cultivation.cf.v1');await setRecurringPractice(helpId,days,time,zone,conditions,trajectoryId,entryId);await onChanged();setMessage('Quedó acordado. Aparecerá en Inicio cuando corresponda; podés cambiarlo, posponerlo o detenerlo.')}catch(e){setError(e instanceof Error?e.message:'No pudimos conservar este ritmo.')}finally{setBusy(false)}}
 return <details className="gm-recurring"><summary>¿Quiero volver a practicarlo?</summary><p>Una invitación en Inicio, a tu ritmo. Sin avisos externos, rachas ni obligación. Repetir no significa hacerlo propio.</p><form onSubmit={e=>{e.preventDefault();onMemory(save)}}><label>Volver cada<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={1}>Día</option><option value={3}>Tres días</option><option value={7}>Semana</option><option value={14}>Dos semanas</option><option value={30}>Mes</option></select></label><label>Hora local<input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label><p>Zona horaria: {zone}</p><label>En qué condiciones me sirve<input maxLength={700} value={conditions} onChange={e=>setConditions(e.target.value)} placeholder="Por ejemplo: si tengo un momento tranquilo"/></label><label><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>Quiero conservar este ritmo y permitir esta invitación en Inicio</label><button disabled={busy||!accepted}>{busy?'Comprobando…':'Acordar mi práctica'}</button></form>{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}</details>
}

export function RecurringThreads({practices,onChanged,onOpen,home=false}:{practices:RecurringPractice[];onChanged:()=>Promise<void>;onOpen:(p:RecurringPractice)=>void;home?:boolean}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('')
 const change=async(p:RecurringPractice,action:string,days=p.recurrence.days,time=p.recurrence.local_time)=>{setBusy(true);setError('');try{await setRecurringPractice(p.help_id,days,time,p.recurrence.timezone,p.recurrence.conditions,p.trajectory_id,p.recurrence.composition_entry_id,p.followup_id,action);await onChanged()}catch(e){setError(e instanceof Error?e.message:'No pudimos cambiar tu práctica.')}finally{setBusy(false)}}
 const visible=home?practices.filter(p=>p.relevant).slice(0,1):practices
 if(!visible.length)return null
 if(home)return <section className="gm-recurring-threads" aria-label="Una práctica, si hoy te sirve"><small>Si hoy te sirve</small><p>{visible[0].title}</p><button onClick={()=>onOpen(visible[0])}>Volver a practicar</button><button disabled={busy} onClick={()=>void change(visible[0],'postpone')}>Otro día</button>{error&&<p role="alert">{error}</p>}</section>
 return <section className="gm-recurring-threads" aria-label="Mis prácticas acordadas">{visible.map(p=><article key={p.followup_id}><small>{p.recurrence.paused?'En pausa':'Si hoy te sirve'}</small><h3>{p.title}</h3>{p.recurrence.conditions&&<p>{p.recurrence.conditions}</p>}<button disabled={busy} onClick={()=>onOpen(p)}>Volver a practicar</button><button disabled={busy} onClick={()=>void change(p,'postpone')}>Posponer un día</button>{!home&&<details><summary>Cambiar mi ritmo</summary><label>Repetir cada<select value={p.recurrence.days} disabled={busy||!p.reminder_allowed} onChange={e=>void change(p,'schedule',Number(e.target.value))}>{[1,3,7,14,30].map(n=><option key={n} value={n}>{n} días</option>)}</select></label><label>Hora local<input type="time" value={p.recurrence.local_time} disabled={busy||!p.reminder_allowed} onChange={e=>void change(p,'schedule',p.recurrence.days,e.target.value)}/></label><p>Invitación en Inicio · {p.recurrence.timezone}</p>{!p.reminder_allowed&&<p>El permiso de recordatorios está retirado. Podés detener este acuerdo o revisar tus permisos.</p>}</details>}{p.recurrence.paused?<button disabled={busy||!p.reminder_allowed} onClick={()=>void change(p,'resume')}>Reanudar</button>:<button disabled={busy} onClick={()=>void change(p,'pause')}>Pausar</button>}<button disabled={busy} onClick={()=>void change(p,'stop')}>No necesito esta práctica</button></article>)}{error&&<p role="alert">{error}</p>}</section>
}
