import {useEffect,useState} from 'react'
import {getConsentState,setConsent} from '../greenfield/application/consent'

export function LearnTogether({authenticated,onLogin,onChanged,onPrivacy}:{authenticated:boolean;onLogin:()=>void;onChanged:()=>Promise<void>;onPrivacy:()=>void}){
 const [enabled,setEnabled]=useState(false),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(authenticated)void getConsentState().then(s=>{setEnabled(Boolean(s?.preferences.evidence_use_allowed));setLoaded(true)}).catch(()=>setError('No pudimos recuperar tu permiso.'))},[authenticated])
 const change=async(value:boolean)=>{setBusy(true);setError('');try{await setConsent('evidence_use',value,'interface.v62.1');const state=await getConsentState();if(state?.preferences.evidence_use_allowed!==value)throw new Error('No pudimos verificar el permiso.');setEnabled(value);await onChanged()}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar tu elección.')}finally{setBusy(false)}}
 return <section className="gm-screen gm-learn"><small>Una decisión tuya</small><h1>Aprender · Juntos</h1><p>Lo que te ayudó puede aportar una señal para acompañar mejor a otras vidas.</p><h2>Qué puede aportar</h2><p>El recurso que viviste, el tipo de situación y tu retorno. Son señales parciales: una experiencia no demuestra que algo sirva para todas las personas.</p><h2>Qué queda privado</h2><p>Tu nombre, lo que escribís, tus notas y el texto de tu Faro. Activar este permiso no los comparte.</p><p>La evidencia autorizada puede contrastar hipótesis de LUMEN. Pueden confirmarse, refutarse o retirarse; no te prometemos un efecto que todavía no vimos.</p>{!authenticated?<button className="gm-primary" onClick={onLogin}>Entrar para elegir</button>:!loaded&&!error?<p role="status">Leyendo tu elección…</p>:<label className="gm-learn-consent"><input type="checkbox" role="switch" checked={enabled} disabled={busy} onChange={e=>void change(e.target.checked)}/> Permitir que mis señales ayuden a aprender</label>}<button className="gm-secondary" onClick={onPrivacy}>Ver o retirar mis permisos</button>{busy&&<p role="status">Comprobando tu elección…</p>}{error&&<p role="alert">{error}</p>}</section>
}
