import {useState} from 'react'
import {useModalFocus} from './useModalFocus'
export type HostAction={label:string;run:()=>void}
export const hostEditorialVersion='lumi.host.2026-10-01.1'
const editorial:Record<string,{name:string;text:string;role:string}>={
 inicio:{name:'Inicio',text:'Es donde empezás: escribís lo que te pasa y escucho antes de proponerte algo. No hace falta ordenar nada.',role:'De acá nacen las posibilidades que después vivís y elegís conservar.'},
 mapa:{name:'Mi Vida',text:'Este es tu mapa vivo. Podés mirar tu dirección, lo vivido y las condiciones de hoy. Toda lectura es provisional y podés corregirla.',role:'La memoria que elegís conservar permite acompañarte con más contexto la próxima vez.'},
 explorar:{name:'Explorar',text:'Esta es la Fuente abierta. Podés mirar por tu cuenta, buscar una palabra y ajustar el tiempo o el formato.',role:'Lo que encontrás puede sumarse a tu Constelación o conservarse en tu Santuario.'},
 tejido:{name:'Tejido',text:'Acá la ayuda puede pasar de una persona a otra. Vos elegís qué pedir, qué ofrecer y con quién encontrarte; sin feed ni ranking.',role:'Lo que te ayudó puede acompañar a otra vida, si vos querés.'},
 santuario:{name:'Santuario',text:'Acá conservás lo que te ayudó y lo que querés tener cerca. Guardar algo y reconocerlo como propio son decisiones distintas.',role:'Cuando reconocés una ayuda como propia, dejo de mediar sobre esa ayuda. Sigo acá para lo que quieras traer.'},
 constelacion:{name:'Constelación',text:'Estas posibilidades parten de una lectura corregible de tu Momento. Podés empezar por una, quitarla o sumar otra.',role:'Lo que vos decís que te sirvió puede cambiar prudentemente el siguiente acompañamiento.'},
 momento:{name:'Momento',text:'Contame lo que estás viviendo, con tus palabras. Podés traer un dolor, un anhelo o algo que todavía no sabés nombrar.',role:'Primero escucho y reflejo como hipótesis; después buscamos qué podría acompañarte.'},
 comprension:{name:'Momento',text:'Esta lectura es una hipótesis. Podés corregir tus palabras y elegir cuánto tiempo tenés antes de ver posibilidades.',role:'Tu presente tiene autoridad sobre cualquier lectura anterior.'},
 vivir:{name:'Vivir',text:'Este espacio es para vivir la posibilidad que elegiste. Podés pausar, salir o volver sin deber nada. Si hay un enlace externo, se avisa antes de abrirlo.',role:'Lo vivido puede convertirse en algo útil para tu vida; vos decidís qué conservar.'},
 retorno:{name:'Retorno',text:'Podés contar cómo fue o seguir sin responder. Dar una señal, guardar y hacer propio son tres gestos separados.',role:'Tus señales consentidas ayudan a ajustar el acompañamiento; el silencio no se interpreta.'},
 faro:{name:'Faro',text:'Tu Faro es una dirección elegida por vos. Podés editarlo, pausarlo o soltarlo; todavía no también es una respuesta válida.',role:'Da contexto a las posibilidades, sin transformarse en un plan obligatorio.'},
 territorio:{name:'Territorio',text:'Podés mirar cualquier área de la vida por curiosidad. No hay una rueda que completar ni áreas que debas trabajar.',role:'El territorio abre otras maneras de acercarte a la Fuente.'},
 aprender:{name:'Aprender · Juntos',text:'Vos elegís si las señales de lo vivido pueden aportar al aprendizaje compartido. Tus textos privados, tu nombre y tu Faro no se comparten.',role:'Las hipótesis de acompañamiento se contrastan y se pueden revisar; no prometen un resultado.'},
 ajustes:{name:'Privacidad y ritmo',text:'Vos elegís qué conservar, qué señales pueden aportar al aprendizaje y cuándo querés un seguimiento. Los permisos son independientes y revocables.',role:'El hilo es tuyo: podés verlo, corregirlo, exportarlo u olvidarlo.'}
}
export function LumiHost({scene,root,quiet,open,onOpen,onClose,actions,thread,onRemember,onRhythm,onMoment}:{scene:string;root:boolean;quiet:boolean;open:boolean;onOpen:()=>void;onClose:()=>void;actions:HostAction[];thread:string;onRemember:()=>void;onRhythm:()=>void;onMoment:(text:string)=>void}){
 const [conversation,setConversation]=useState(false),[draft,setDraft]=useState('')
 const [firstHelp,setFirstHelp]=useState(()=>localStorage.getItem('lumen.host.help.v1.'+scene)!=='seen')
 const copy=editorial[scene]||editorial.inicio
 useModalFocus(open,onClose)
 const act=(run:()=>void)=>{onClose();run()}
 return <><button className={`gm-lumi-orb ${root?'at-door':'at-scene'} ${scene==='inicio'?'at-home':''} ${quiet?'is-quiet':''}`} aria-label="LUMI: opciones y ayuda de este espacio" aria-expanded={open} aria-controls="lumi-space-sheet" onClick={()=>{setConversation(false);setFirstHelp(false);localStorage.setItem('lumen.host.help.v1.'+scene,'seen');onOpen()}}><span aria-hidden="true"/></button>{firstHelp&&!quiet&&!open&&<span className={`gm-lumi-hint ${scene==='inicio'?'at-home':root?'at-door':'at-scene'}`}>Opciones y ayuda con LUMI</span>}{open&&<div className="gm-lumi-backdrop" onClick={onClose}><section id="lumi-space-sheet" className="gm-lumi-sheet" role="dialog" aria-modal="true" aria-label={`LUMI · ${copy.name}`} data-editorial-version={hostEditorialVersion} onClick={e=>e.stopPropagation()}><header><span className="gm-lumi-mini" aria-hidden="true"/><h2>LUMI · {copy.name}</h2><button aria-label="Cerrar LUMI" onClick={onClose}>×</button></header>{conversation?<><h3>Seguimos desde acá</h3><p>{thread}</p><button onClick={()=>act(onRemember)}>Ver y corregir lo que recuerdo</button><form onSubmit={e=>{e.preventDefault();if(draft.trim()){act(()=>onMoment(draft.trim()));setDraft('')}}}><label>¿Qué querés traer ahora?<textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Con tus palabras…"/></label><button className="gm-primary" disabled={!draft.trim()}>Contar a LUMI</button></form><button onClick={()=>setConversation(false)}>Volver a las opciones de este espacio</button></>:<><h3>Desde acá podés</h3><div className="gm-lumi-actions">{actions.slice(0,5).map(a=><button key={a.label} onClick={()=>act(a.run)}>{a.label}</button>)}</div><h3>Cómo funciona este espacio</h3><p>{copy.text}</p><details><summary>Leer la transcripción</summary><p>{copy.text}</p><p>{copy.role}</p></details><h3>Cómo juega en LUMEN</h3><p>{copy.role}</p><footer><button onClick={()=>setConversation(true)}>Hablar con LUMI</button><button onClick={()=>act(onRhythm)}>Cómo te acompaño</button></footer></>}</section></div>}</>
}
