import {useState} from 'react'
import {setLifeContext,type MovementSnapshot} from '../greenfield/application/movement'

export function Movement({snapshot,onChanged,onPrivacy}:{snapshot:MovementSnapshot|null;onChanged:()=>Promise<void>;onPrivacy:()=>void}){
 const [editing,setEditing]=useState(false),[adjustable,setAdjustable]=useState(''),[external,setExternal]=useState(''),[potential,setPotential]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const edit=()=>{setAdjustable(snapshot?.context.adjustable||'');setExternal(snapshot?.context.external||'');setPotential(snapshot?.context.potential||'');setEditing(true)}
 const save=async()=>{setBusy(true);setError('');try{await setLifeContext(adjustable,external,potential);await onChanged();setEditing(false)}catch(e){setError(e instanceof Error?e.message:'No pudimos conservar tu lectura.')}finally{setBusy(false)}}
 if(snapshot?.state==='without_memory')return <p>Podés habitar el presente sin conservar una historia. <button onClick={onPrivacy}>Ver mis permisos</button></p>
 return <div className="gm-movement">{Boolean(snapshot?.items.length)&&<details><summary>Tu movimiento</summary>{snapshot?.items.map(f=><p key={f.event_id} data-evidence-event={f.event_id}>{f.text}</p>)}<button onClick={onPrivacy}>Ver y corregir lo que recuerdo</button></details>}{Boolean(snapshot?.changes.length)&&<details><summary>Cómo cambió mi acompañamiento</summary>{snapshot?.changes.map(f=><p key={f.event_id} data-evidence-event={f.event_id}>{f.text}</p>)}<button onClick={onPrivacy}>Ver y corregir lo que recuerdo</button></details>}<details><summary>Mi contexto, con mis palabras</summary>{editing?<><label>Puedo ajustar<textarea maxLength={1000} value={adjustable} onChange={e=>setAdjustable(e.target.value)}/></label><label>No depende de mí<textarea maxLength={1000} value={external} onChange={e=>setExternal(e.target.value)}/></label><label>Qué puedo poner en juego<textarea maxLength={1000} value={potential} onChange={e=>setPotential(e.target.value)}/></label><p>Esta lectura la escribís vos. Podés cambiarla o dejarla vacía; no define quién sos.</p><button disabled={busy} onClick={()=>void save()}>Guardar mi lectura</button><button disabled={busy} onClick={()=>setEditing(false)}>Cancelar</button></>:<><h3>Puedo ajustar</h3><p>{snapshot?.context.adjustable||'Todavía no compartiste algo que puedas ajustar.'}</p><h3>No depende de mí</h3><p>{snapshot?.context.external||'Podés reconocer lo que está fuera de tu alcance.'}</p>{snapshot?.context.potential&&<><h3>Qué puedo poner en juego</h3><p>{snapshot.context.potential}</p></>}<button onClick={edit}>Corregir o escribir mi contexto</button></>}{error&&<p role="alert">{error}</p>}</details></div>
}
