import {useCallback,useEffect,useRef,useState} from 'react'
import { getAuthSnapshot, requestEmailOtp, verifyEmailOtp } from '../greenfield/application/auth'
import { bootstrapPerson } from '../greenfield/application/consent'
import { accompanyMoment, selectHelp, recordOutcome, type OutcomeEffect } from '../greenfield/application/s1'
import { composeMomentConstellation } from '../greenfield/application/moment'
import { createTrajectory, createTrajectoryFromMoment, updateTrajectory, getContinuitySnapshot, setMemory, getSourceTaxonomy, listSanctuary, saveSanctuary, discoverSource, type SourceItem, type SanctuaryEntry } from '../greenfield/application/embryo'
import { getLifeMap, type LifeMapSnapshot } from '../greenfield/application/life-map'
import { Experience } from './Experience'
import { premiumFamily, premiumFamilyLabel } from './premium-source'
import './premium-vnext.css'

type Scene='inicio'|'momento'|'mapa'|'faro'|'constelacion'|'vivir'|'retorno'|'santuario'|'territorio'|'impacto'

const art={
 hero:'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=90',
 moment:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=90',
 map:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=90',
 faro:'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=90',
 family:'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1200&q=90',
 calm:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd4297?auto=format&fit=crop&w=1200&q=90'
}
const nav=[['⌂','Inicio','inicio'],['◇','Explorar','territorio'],['♡','Mi Vida','mapa'],['♧','Comunidad','impacto'],['▤','Biblioteca','constelacion']] as const
const areas=['Bienestar físico y mental','Trabajo y propósito','Relaciones','Familia y hogar','Desarrollo personal','Creatividad','Comunidad y servicio','Entorno y naturaleza','Finanzas y recursos']

function Chrome({scene,go,children,back,account,authReady}:{scene:Scene,go:(s:Scene)=>void,children:React.ReactNode,back?:()=>void,account:()=>void,authReady:boolean}){
 return <main className="gm-stage"><div className="gm-phone"><header className="gm-top">{back?<button aria-label="Volver" onClick={back}>‹</button>:<span/>}<b>LUMEN</b><button aria-label="Cuenta" disabled={!authReady} onClick={account}>◎</button></header><div className="gm-content">{children}</div><nav className="gm-nav">{nav.map(([i,l,s])=><button key={l} className={scene===s?'on':''} onClick={()=>go(s as Scene)}><i>{i}</i><small>{l}</small></button>)}</nav></div></main>
}
export default function PremiumVNext(){
 const [scene,setScene]=useState<Scene>('inicio')
 const [moment,setMoment]=useState('')
 const [feedback,setFeedback]=useState('Me ayudó')
 const [filter,setFilter]=useState('Todas')
 const [episodeId,setEpisodeId]=useState<string|null>(null)
 const [momentId,setMomentId]=useState<string|null>(null)
 const [capacityKeys,setCapacityKeys]=useState<string[]>([])
 const [liveResources,setLiveResources]=useState<SourceItem[]>([])
 const [constellationFromMoment,setConstellationFromMoment]=useState(false)
 const [chosen,setChosen]=useState<SourceItem|null>(null)
 const [sanctuaryEntries,setSanctuaryEntries]=useState<SanctuaryEntry[]>([])
 const [note,setNote]=useState('')
 const [faro,setFaro]=useState('')
 const [trajectoryId,setTrajectoryId]=useState<string|null>(null)
 const [editingFaro,setEditingFaro]=useState(false)
 const [sanctuaryTab,setSanctuaryTab]=useState('Recursos')
 const typeBucket=(item:SourceItem)=>{const family=premiumFamily(item);if(family==='audio_practice'||family==='contemplative_reading_audio')return 'Audios';if(family==='classic_reading'||family==='illustrated_guide'||family==='health_reference')return 'Lecturas';const v=item.help_type.toLowerCase();if(v.includes('audio'))return 'Audios';if(v.includes('read')||v.includes('text')||v.includes('guide')||v.includes('article'))return 'Lecturas';if(v.includes('practice')||v.includes('exercise')||v.includes('ritual')||v.includes('meditation'))return 'Prácticas';return 'Experiencias'}
 const sourceLabel=(item:SourceItem)=>premiumFamily(item)?premiumFamilyLabel(item):({practice:'Práctica',reading:'Lectura',reflection:'Reflexión',question:'Pregunta',tool:'Herramienta',conversation:'Conversación',human_action:'Acción en la vida',professional_support:'Apoyo profesional',institutional_service:'Servicio',external_resource:'Recurso externo'}[item.help_type]||item.help_type.replaceAll('_',' '))
 const visibleSanctuary=sanctuaryEntries.filter(e=>sanctuaryTab==='Notas'?e.entry_kind==='note':sanctuaryTab==='Reflexiones'?e.entry_kind==='reflection':sanctuaryTab==='Recursos'?e.entry_kind==='treasure':Boolean(e.source_help_id))
 const [busy,setBusy]=useState(false)
 const [authenticated,setAuthenticated]=useState(false)
 const [authReady,setAuthReady]=useState(false)
 const [authOpen,setAuthOpen]=useState(false)
 const [email,setEmail]=useState('')
 const [otp,setOtp]=useState('')
 const [otpSent,setOtpSent]=useState(false)
 const [pendingAction,setPendingAction]=useState<null|(()=>Promise<void>)>(null)
 const [error,setError]=useState('')
 const [lifeMap,setLifeMap]=useState<LifeMapSnapshot|null>(null)
 const [memoryOpen,setMemoryOpen]=useState(false)
 const [memoryAction,setMemoryAction]=useState<null|(()=>Promise<void>)>(null)
 const outcomeRecorded=useRef(false)
 const savedEntryId=useRef<string|null>(null)
 const hydrate=useCallback(async()=>{
  const [continuity,entries,map]=await Promise.all([getContinuitySnapshot(),listSanctuary(),getLifeMap()])
  const active=continuity.trajectories.find(t=>t.status==='active')
  if(active){setFaro(active.faro_text);setTrajectoryId(active.trajectory_id)}
  setSanctuaryEntries(entries);setLifeMap(map)
 },[])
 useEffect(()=>{void getAuthSnapshot().then(async a=>{if(a.session){await bootstrapPerson();setAuthenticated(true);await hydrate()}}).catch(()=>setError('No pudimos recuperar tu información. Volvé a intentarlo.')).finally(()=>setAuthReady(true))},[hydrate])
 const requireAuth=(action:()=>Promise<void>)=>{if(authenticated){void action();return}setPendingAction(()=>action);setAuthOpen(true)}
 const sendOtp=async()=>{setBusy(true);setError('');try{await requestEmailOtp(email);setOtpSent(true)}catch(e){setError(e instanceof Error?e.message:'No pudimos enviar el código')}finally{setBusy(false)}}
 const confirmOtp=async()=>{setBusy(true);setError('');try{const a=await verifyEmailOtp(email,otp);if(!a.session)throw new Error('No se pudo iniciar sesión');await bootstrapPerson();setAuthenticated(true);setAuthOpen(false);setOtpSent(false)}catch(e){setError(e instanceof Error?e.message:'No se pudo verificar el código');setBusy(false);return}try{await hydrate()}catch{setError('Entraste, pero no pudimos recuperar tu información. Reintentá al abrir Mi Vida.')}const action=pendingAction;setPendingAction(null);if(action)await action();setBusy(false)}
 const submitMoment=async()=>{setBusy(true);setError('');try{const s=await accompanyMoment(moment);if(!s.episode_id||!s.moment_id)throw new Error('Momento incompleto');if(s.safety?.state==='blocked'){setError('Este momento necesita acompañamiento humano inmediato.');return}if(s.scene_id==='moment.clarify'){setError('Para acompañarte mejor, contanos un poco más sobre el área de tu vida y qué te gustaría cultivar.');return}if(s.scene_id==='moment.no_match'){setError('Todavía no encontramos una posibilidad adecuada. Podés contar más sobre lo que necesitás.');return}setEpisodeId(s.episode_id);setMomentId(s.moment_id);setCapacityKeys(s.interpretation?.capacity_keys||[]);const constellation=await composeMomentConstellation(s.episode_id,s.interpretation?.capacity_keys||[]);setLiveResources(constellation.items||[]);setConstellationFromMoment(Boolean(constellation.items?.length));setLifeMap(await getLifeMap());go('mapa')}catch(e){setError(e instanceof Error?e.message:'No pudimos procesar este momento')}finally{setBusy(false)}}
 const ensureTrajectory=async()=>{if(trajectoryId)return trajectoryId;const t=momentId?await createTrajectoryFromMoment(faro,capacityKeys,momentId):await createTrajectory(faro);setTrajectoryId(t.trajectory_id);return t.trajectory_id}
 const saveFaro=async()=>{if(!faro.trim()){setError('Escribí una orientación para guardar tu Faro.');return}setBusy(true);setError('');try{const id=await ensureTrajectory();await updateTrajectory(id,faro,'active');const snapshot=await getContinuitySnapshot();const saved=snapshot.trajectories.find(t=>t.trajectory_id===id);if(saved?.faro_text!==faro.trim())throw new Error('No pudimos verificar el Faro guardado');setLifeMap(await getLifeMap());setEditingFaro(false)}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar tu Faro')}finally{setBusy(false)}}
 const openConstellation=async()=>{setError('');if(!trajectoryId&&!faro.trim()){setEditingFaro(true);setError('Escribí una orientación para abrir tu constelación.');return}try{await ensureTrajectory();if(!liveResources.length){setLiveResources(await discoverSource(null,null,null,'es-AR',12));setConstellationFromMoment(false)}setScene('constelacion')}catch(e){setError(e instanceof Error?e.message:'No pudimos abrir la constelación')}}
 const chooseHelp=async(item:SourceItem)=>{setBusy(true);setError('');try{if(episodeId&&constellationFromMoment)await selectHelp(episodeId,item.help_id,'selected');else setEpisodeId(null);setChosen(item);outcomeRecorded.current=false;savedEntryId.current=null;go('vivir')}catch(e){setError(e instanceof Error?e.message:'No pudimos abrir esta posibilidad')}finally{setBusy(false)}}
 const finish=()=>go('retorno')
 const saveReturn=async()=>{setBusy(true);setError('');try{if(episodeId&&!outcomeRecorded.current){const effect:OutcomeEffect=feedback==='Me ayudó mucho'||feedback==='Me ayudó'?'helped':feedback==='No mucho'||feedback==='No me sirvió'?'not_helped':'unsure';await recordOutcome(episodeId,effect);outcomeRecorded.current=true}const title=chosen?.title||'Reflexión sobre mi experiencia';if(!savedEntryId.current){const saved=await saveSanctuary('reflection',title,note||feedback,chosen?.help_id||null);savedEntryId.current=saved.entry_id}const entries=await listSanctuary();if(!entries.some(e=>e.entry_id===savedEntryId.current))throw new Error('El guardado todavía no pudo verificarse. Reintentá la lectura.');setSanctuaryEntries(entries);setLifeMap(await getLifeMap());setSanctuaryTab('Reflexiones');go('santuario')}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar el retorno')}finally{setBusy(false)}}
 const requireMemory=async(action:()=>Promise<void>)=>{setError('');try{const state=await getContinuitySnapshot();if(state.memory_allowed){await action();return}setMemoryAction(()=>action);setMemoryOpen(true)}catch(e){setError(e instanceof Error?e.message:'No pudimos comprobar tu preferencia de memoria')}}
 const confirmMemory=async()=>{setBusy(true);setError('');try{await setMemory(true);setMemoryOpen(false);const action=memoryAction;setMemoryAction(null);if(action)await action()}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar tu preferencia')}finally{setBusy(false)}}
 const exploreArea=async(label:string)=>{setBusy(true);setError('');try{const taxonomy=await getSourceTaxonomy();const direct:Record<string,string>={'Bienestar físico y mental':'wellbeing','Trabajo y propósito':'work','Relaciones':'relationships','Familia y hogar':'family_care','Desarrollo personal':'learning_growth','Finanzas y recursos':'economy'};const key=direct[label]||taxonomy.areas.find(a=>a.label===label)?.key||null;setLiveResources(await discoverSource(key,null,null,'es-AR',40));setConstellationFromMoment(false);setScene('constelacion')}catch(e){setError(e instanceof Error?e.message:'No pudimos explorar esta área. Reintentá.')}finally{setBusy(false)}}
 const go=(s:Scene)=>{if(s==='constelacion'&&!liveResources.length){setBusy(true);void discoverSource(null,null,null,'es-AR',12).then(items=>{setLiveResources(items);setConstellationFromMoment(false)}).catch(()=>setError('No pudimos cargar las posibilidades. Reintentá desde el Territorio.')).finally(()=>setBusy(false))}setScene(s)}
 let body:React.ReactNode
 if(scene==='inicio') body=<section className="gm-screen gm-home" style={{backgroundImage:`linear-gradient(0deg,rgba(15,22,18,.62),rgba(15,22,18,.05)),url(${art.hero})`}}><div className="gm-home-copy"><h1>Una vida más tuya.</h1><p>Recursos, prácticas y personas para volver al cuerpo, habitar el presente y crear una vida más consciente.</p><button className="gm-entry" onClick={()=>go('momento')}>Cuéntame en qué momento estás... <i>→</i></button><div className="gm-pills">{['Me siento estresado','Necesito claridad','Quiero avanzar en algo','Solo quiero explorar'].map((x,i)=><button key={x} onClick={()=>go(i===3?'territorio':'momento')}>{x}</button>)}</div></div></section>
 else if(scene==='momento') body=<section className="gm-screen gm-moment" style={{backgroundImage:`linear-gradient(0deg,rgba(20,24,20,.52),rgba(20,24,20,.06)),url(${art.moment})`}}><div className="gm-overlay"><small>Tu Momento</small><h1>¿Qué estás viviendo hoy?</h1><p>Escribe con libertad. No hay respuestas correctas. LUMEN te escucha.</p><textarea value={moment} onChange={e=>setMoment(e.target.value)}/><div className="gm-tools"><span>◉</span><span>▧</span><span>▣</span><button disabled={busy} aria-label="Continuar" onClick={()=>requireAuth(submitMoment)}>{busy?'…':'→'}</button>{error&&<small className="gm-error">{error}</small>}</div></div></section>
 else if(scene==='mapa') body=<section className="gm-screen gm-map" style={{backgroundImage:`linear-gradient(0deg,rgba(20,29,24,.38),rgba(20,29,24,.08)),url(${art.map})`}}><h1>Mi Mapa Vivo</h1><p>Una comprensión de tu vida que evoluciona contigo.</p><div className="gm-tabs"><b>Vista general</b><span>Dirección</span><span>Potencial</span><span>Realización</span><span>Condiciones</span></div><div className="gm-lenses"><article><i>♧</i><b>Dirección</b><small>Lo que importa</small></article><article><i>❧</i><b>Potencial</b><small>Lo que puedes desplegar</small></article><article><i>≈</i><b>Condiciones</b><small>Lo que habilita o restringe</small></article><article><i>☼</i><b>Realización</b><small>Lo que vives hoy</small></article></div><div className="gm-caption">{lifeMap?.epistemic_note||'Esta es una visión en construcción. Se va enriqueciendo con cada momento.'}</div>{lifeMap?.memory_allowed&&<div className="gm-map-memory">{lifeMap.direction.map(d=><p key={d.faro_id}>{d.text}</p>)}{lifeMap.realization.length>0&&<p>Tu último retorno: {lifeMap.realization[0].effect==='helped'?'te ayudó':lifeMap.realization[0].effect==='not_helped'?'no te ayudó':'todavía no lo sabés'}.</p>}</div>}<button className="gm-primary" onClick={()=>go('faro')}>Ver mi Faro</button></section>
 else if(scene==='faro') body=<section className="gm-screen gm-faro" style={{backgroundImage:`linear-gradient(0deg,rgba(14,21,18,.68),rgba(14,21,18,.06)),url(${art.faro})`}}><div className="gm-faro-main"><h1>Mi Faro</h1><p>Tu orientación actual.</p>{editingFaro?<textarea value={faro} onChange={e=>setFaro(e.target.value)} placeholder="¿Qué querés cuidar o cultivar?"/>:<blockquote>{faro||'Todavía no definiste tu Faro.'}</blockquote>}<button onClick={()=>editingFaro?requireAuth(saveFaro):setEditingFaro(true)}>{editingFaro?'Guardar mi Faro':'Editar mi Faro'}</button>{error&&<small className="gm-error">{error}</small>}</div><div className="gm-next"><b>Próximos pasos sugeridos</b><button onClick={()=>requireAuth(openConstellation)}>Explorar más sobre este Faro <i>›</i></button><button onClick={()=>go('mapa')}>Ver cómo se conecta con tu vida actual <i>›</i></button><button onClick={()=>requireAuth(openConstellation)}>Abrir una constelación para avanzar <i>›</i></button></div></section>
 else if(scene==='constelacion') body=<section className="gm-screen gm-list"><header style={{backgroundImage:`linear-gradient(0deg,rgba(14,21,18,.72),rgba(14,21,18,.08)),url(${art.calm})`}}><h1>Tu Constelación</h1><p>Posibilidades disponibles para explorar con libertad.</p></header><div className="gm-filters">{['Todas','Prácticas','Lecturas','Audios','Experiencias'].map(x=><button className={filter===x?'on':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="gm-resources">{liveResources.filter(r=>filter==='Todas'||typeBucket(r)===filter).map(r=><button key={r.help_id} onClick={()=>void chooseHelp(r)}><img src={art.calm} alt=""/><span><small>{sourceLabel(r)}</small><b>{r.title}</b><em>{r.duration_minutes?`${r.duration_minutes} min · `:''}{(r.areas||[]).join(' · ')}</em></span><i>›</i></button>)}</div>{liveResources.length===0&&<div className="gm-empty">Todavía no hay posibilidades disponibles. Explorá otra área del Territorio.</div>}</section>
 else if(scene==='vivir') body=chosen?<Experience key={chosen.help_id} help={chosen} onExit={()=>go('constelacion')} onComplete={finish}/>:<section className="gm-screen gm-live"><p>Elegí una posibilidad de tu Constelación para vivirla.</p><button onClick={()=>go('constelacion')}>Volver a la Constelación</button></section>
 else if(scene==='retorno') body=<section className="gm-screen gm-return"><h1>¿Cómo fue?</h1><p>Tu experiencia nos ayuda a acompañarte mejor.</p><div className="gm-faces">{[['◉','Me ayudó mucho'],['◡','Me ayudó'],['•','Algo'],['⌢','No mucho'],['×','No me sirvió']].map(([f,l])=><button key={l} aria-label={l} className={feedback===l?'on':''} onClick={()=>setFeedback(l)}><i aria-hidden="true">{f}</i><small aria-hidden="true">{l}</small></button>)}</div><b className="gm-label">Cuéntame más sobre tu experiencia...</b><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="¿Qué fue lo más valioso? ¿Qué fue difícil? ¿En qué te gustaría profundizar?"/><div className="gm-note">Lo que conserves queda en tu Santuario. Compartir evidencia requiere un consentimiento aparte.</div>{error&&<small className="gm-error">{error}</small>}<button className="gm-primary" disabled={busy} onClick={()=>requireAuth(()=>requireMemory(saveReturn))}>{busy?'Guardando…':'Guardar en mi Santuario'}</button></section>
 else if(scene==='santuario') body=<section className="gm-screen gm-list gm-sanctuary"><header style={{backgroundImage:`linear-gradient(0deg,rgba(14,21,18,.64),rgba(14,21,18,.08)),url(${art.moment})`}}><h1>Mi Santuario</h1><p>Tu espacio personal de lo significativo y propio.</p></header><div className="gm-san-tabs">{['Recursos','Experiencias','Reflexiones','Notas'].map(x=><button key={x} className={sanctuaryTab===x?'on':''} onClick={()=>setSanctuaryTab(x)}>{x}</button>)}</div><div className="gm-resources">{authenticated&&visibleSanctuary.map(r=><article key={r.entry_id}><img src={art.calm} alt=""/><span><b>{r.title||'Reflexión'}</b><em>Guardado en tu Santuario</em><small>{r.content}</small></span><i>♡</i></article>)}</div>{authenticated?visibleSanctuary.length===0&&<div className="gm-empty">Todavía no hay elementos en esta sección.</div>:<div className="gm-empty">Entrá a tu cuenta para recuperar lo que conservaste.</div>}</section>
 else if(scene==='territorio') body=<section className="gm-screen gm-territory" style={{backgroundImage:`linear-gradient(0deg,rgba(14,21,18,.62),rgba(14,21,18,.14)),url(${art.map})`}}><h1>Explorar el Territorio</h1><p>Áreas de la vida para inspirarte y orientar tu camino.</p>{error&&<p role="alert" className="gm-error">{error}</p>}<div className="gm-areas">{areas.map((a,i)=><button key={a} disabled={busy} onClick={()=>void exploreArea(a)} style={{backgroundImage:`linear-gradient(0deg,rgba(15,23,19,.58),rgba(15,23,19,.04)),url(${[art.calm,art.faro,art.family,art.hero,art.moment,art.map][i%6]})`}}>{a}</button>)}</div></section>
 else body=<section className="gm-screen gm-impact" style={{backgroundImage:`linear-gradient(0deg,rgba(13,20,17,.72),rgba(13,20,17,.18)),url(${art.family})`}}><div><h1>Impacto y Aprendizaje</h1><p>Tu experiencia contribuye. Juntos hacemos que LUMEN evolucione para servir mejor a todos.</p>{[['Vidas reales','Personas que comparten sus experiencias.'],['Aprendizaje colectivo','Identificamos patrones que realmente ayudan.'],['Mejores acompañamientos','LUMEN evoluciona para servir mejor.']].map(x=><article key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></article>)}<blockquote>“Tu camino no solo transforma tu vida. También ilumina el camino de otros.”</blockquote></div></section>
 return <><Chrome scene={scene} go={go} back={scene==='momento'?()=>go('inicio'):undefined} account={()=>authenticated?go('santuario'):setAuthOpen(true)} authReady={authReady}>{body}</Chrome>{memoryOpen&&<div className="gm-auth" role="dialog" aria-modal="true" aria-label="Memoria personal"><div><h2>¿Querés conservarlo?</h2><p>Activar la memoria permite guardar y recuperar lo significativo en tu Santuario y Mapa Vivo. No habilita compartirlo ni usarlo para aprendizaje colectivo.</p><button className="gm-primary" disabled={busy} onClick={()=>void confirmMemory()}>Activar memoria y guardar</button><button disabled={busy} onClick={()=>{setMemoryOpen(false);setMemoryAction(null)}}>Ahora no</button>{error&&<small role="alert" className="gm-error">{error}</small>}</div></div>}{authOpen&&<div className="gm-auth" role="dialog" aria-modal="true" aria-label="Entrar a LUMEN"><div><button className="gm-auth-close" aria-label="Cerrar" onClick={()=>{setAuthOpen(false);setPendingAction(null)}}>×</button><b>LUMEN</b><h2>Entrá para continuar tu camino</h2><p>Tu Momento, Mapa Vivo y Santuario son personales.</p><input aria-label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@email.com"/>{otpSent&&<input aria-label="Código" inputMode="numeric" value={otp} onChange={e=>setOtp(e.target.value)} placeholder="Código recibido"/>}{error&&<small className="gm-error">{error}</small>}<button className="gm-primary" disabled={busy} onClick={()=>void(otpSent?confirmOtp():sendOtp())}>{busy?'…':otpSent?'Entrar':'Enviar código'}</button></div></div>}</>
}
