import { useMemo, useState } from 'react'
import './premium-vnext.css'

type Scene='inicio'|'momento'|'mapa'|'faro'|'constelacion'|'vivir'|'retorno'|'santuario'|'territorio'|'aprender'
const scenes:Scene[]=['inicio','momento','mapa','faro','constelacion','vivir','retorno','santuario','territorio','aprender']
const labels:Record<Scene,string>={inicio:'Inicio',momento:'Momento',mapa:'Mapa Vivo',faro:'Faro',constelacion:'Constelación',vivir:'Vivir',retorno:'Retorno',santuario:'Santuario',territorio:'Territorio',aprender:'Aprender'}
const art={
 hero:'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=2200&q=92',
 family:'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1600&q=88',
 walk:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=88',
 calm:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd4297?auto=format&fit=crop&w=1600&q=88',
 journal:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1600&q=88',
}
function Mark(){return <div className="vx-mark"><b>LUMEN</b><small>UN HOGAR PARA LA VIDA</small></div>}
function Rail({scene,setScene}:{scene:Scene,setScene:(s:Scene)=>void}){return <aside className="vx-rail"><Mark/><nav>{scenes.map((s,i)=><button className={scene===s?'on':''} onClick={()=>setScene(s)} key={s}><span>{String(i+1).padStart(2,'0')}</span>{labels[s]}</button>)}</nav><p>Una vida no se completa.<br/>Se vive, se comprende<br/>y vuelve a abrirse.</p></aside>}
function Shell({scene,setScene,children}:{scene:Scene,setScene:(s:Scene)=>void,children:React.ReactNode}){const i=scenes.indexOf(scene);return <div className="vx"><Rail scene={scene} setScene={setScene}/><main>{children}<div className="vx-step"><button disabled={i===0} onClick={()=>setScene(scenes[i-1])}>←</button><span>{i+1} / {scenes.length}</span><button disabled={i===scenes.length-1} onClick={()=>setScene(scenes[i+1])}>→</button></div></main></div>}
function Inicio({go}:{go:(s:Scene)=>void}){const [v,setV]=useState('');return <section className="vx-home"><div className="vx-home-art" style={{backgroundImage:`linear-gradient(90deg,rgba(18,25,20,.12),rgba(18,25,20,.02)),url(${art.hero})`}}><div className="vx-top"><Mark/><span>Tu espacio</span></div><div className="vx-home-copy"><p>TU VIDA · AHORA</p><h1>¿Qué está presente<br/>en tu vida hoy?</h1><h2>No hace falta saber por dónde empezar.<br/>Podemos mirar juntos.</h2><div className="vx-input"><input value={v} onChange={e=>setV(e.target.value)} placeholder="Contame qué está pasando..."/><button onClick={()=>go('momento')}>→</button></div><div className="vx-chips"><button onClick={()=>setV('Necesito claridad')}>Necesito claridad</button><button onClick={()=>setV('Algo me preocupa')}>Algo me preocupa</button><button onClick={()=>go('territorio')}>Quiero mirar mi vida</button><button onClick={()=>setV('Solo quiero estar')}>Solo quiero estar</button></div></div><blockquote>“No venís a gestionar tu vida.<br/>Venís a encontrarte con ella.”</blockquote></div></section>}
function Momento(){return <section className="vx-page vx-conversation"><header><p>MOMENTO · ESCUCHAR</p><h1>Estoy acá.</h1><span>Contame a tu manera. No necesito encajarte en una categoría.</span></header><div className="vx-dialog"><div className="person">Estoy agotado. Siento que mis hijos están creciendo y yo me lo estoy perdiendo.</div><div className="lumi"><i>LUMI</i><p>Suena a que no es sólo cansancio. Hay algo muy valioso para vos que sentís que está pasando mientras tu energía queda en otro lado.</p><p>Podemos mirar esto sin convertirlo enseguida en un problema a corregir.</p></div></div><div className="vx-understanding"><small>LO QUE EMPIEZO A COMPRENDER · PROVISIONAL</small><b>Familia y trabajo están tensando algo que importa: presencia, tiempo compartido y una etapa que no querés dejar pasar.</b><span>Podés corregirme en cualquier momento.</span></div></section>}
function Mapa(){return <section className="vx-page"><header><p>MAPA VIVO · COMPRENDER</p><h1>Tu vida no es una lista.</h1><span>El mapa aparece sólo hasta donde ayuda a ver mejor.</span></header><div className="vx-map"><article><small>DIRECCIÓN</small><h2>Lo que importa</h2><b>Estar realmente presente durante estos años con tus hijos.</b><p>Amor · presencia · cuidado · disfrute</p></article><article><small>POTENCIAL</small><h2>Lo que puede desplegarse</h2><b>Conectás con facilidad a través del juego y la conversación.</b><p>La regulación y los límites pueden necesitar cultivo.</p></article><article><small>REALIZACIÓN</small><h2>Lo que está ocurriendo</h2><b>Los domingos juntos funcionan. El teléfono invade las noches.</b><p>Hay vida valiosa que ya existe.</p></article><article><small>CONDICIONES</small><h2>Lo que habilita o restringe</h2><b>Trabajo exigente, poco sueño y una pareja que acompaña.</b><p>No todo se resuelve “trabajando en vos”.</p></article></div><div className="vx-mapnote">Este mapa no te define. Es una comprensión viva, parcial y corregible.</div></section>}
function Faro(){return <section className="vx-page vx-faro"><div className="vx-photo" style={{backgroundImage:`linear-gradient(90deg,rgba(24,31,25,.78),rgba(24,31,25,.12)),url(${art.family})`}}><p>ORIENTAR · FARO</p><h1>Algo que vale<br/>la pena cuidar.</h1><div className="vx-faro-card"><small>TU FARO · EDITABLE</small><b>“Quiero estar realmente presente durante esta etapa de la vida de mis hijos.”</b><p>No es una meta que LUMEN te impone. Es una dirección que vos reconocés y podés cambiar o soltar.</p><button>Esto me representa</button><button className="quiet">Quiero decirlo distinto</button></div></div></section>}
function Constelacion(){const cards=[['COMPRENDER','Una lectura breve','Por qué el cansancio vuelve más difícil estar presente.',art.journal],['PRACTICAR','Cruzar el umbral','Una práctica de 4 minutos para llegar a casa antes que tu cabeza.',art.calm],['VIVIR','Una hora que sea de ustedes','Una experiencia simple para este fin de semana.',art.family],['CONECTAR','Hablarlo con alguien','Una conversación posible sobre límites y carga.',art.walk]];return <section className="vx-page"><header><p>ABRIR · CONSTELACIÓN</p><h1>No una respuesta.<br/>Varias posibilidades.</h1><span>Elegidas por cómo podrían ayudar a esta Vida ahora. Podés mover, quitar o ignorar cualquiera.</span></header><div className="vx-constellation">{cards.map(([k,t,d,img])=><article key={t} style={{backgroundImage:`linear-gradient(0deg,rgba(17,23,19,.86),rgba(17,23,19,.03)),url(${img})`}}><small>{k}</small><h2>{t}</h2><p>{d}</p><button>→</button></article>)}</div><p className="vx-whisper">También puede ser que hoy no necesites hacer nada.</p></section>}
function Vivir(){return <section className="vx-page vx-live"><div className="vx-photo" style={{backgroundImage:`linear-gradient(90deg,rgba(19,27,22,.76),rgba(19,27,22,.08)),url(${art.walk})`}}><p>VIVIR · FUERA DE LUMEN</p><h1>Cruzar el umbral.</h1><h2>Antes de entrar a casa, cuatro minutos para dejar que termine una cosa antes de empezar otra.</h2><div className="vx-practice"><span>04:00</span><p>Guardá el teléfono. Sentí el cuerpo. No busques calmarte. Sólo reconocé que estás llegando.</p><button>Empezar</button></div><blockquote>Después cerrá LUMEN.<br/>Lo importante ocurre allá afuera.</blockquote></div></section>}
function Retorno(){return <section className="vx-page vx-return"><header><p>RETORNO · CÓMO FUE</p><h1>¿Qué pasó en la vida?</h1><span>No es una evaluación. Una señal alcanza.</span></header><div className="vx-returncard"><p>La última vez elegiste <b>Cruzar el umbral</b>.</p><div><button>Me ayudó</button><button>Algo</button><button>No me ayudó</button><button>No lo hice</button></div><textarea placeholder="Si querés, contame qué notaste..."/><small>Podés dejarlo acá. LUMEN no necesita más de vos.</small></div></section>}
function Santuario(){return <section className="vx-page"><header><p>INTEGRAR · SANTUARIO</p><h1>Algo de esto<br/>ya es tuyo.</h1><span>Guardás lo que querés conservar. No porque LUMEN lo necesite, sino porque puede volver a servirte.</span></header><div className="vx-sanctuary"><article className="big"><small>EXPERIENCIA PROPIA</small><h2>“Cuatro minutos antes de entrar.”</h2><p>Me ayuda especialmente los días en que termino trabajando tarde. No necesito hacerlo perfecto.</p><span>Guardado por vos · reutilizable</span></article><article><small>FARO</small><h2>Estar presente en esta etapa.</h2></article><article><small>REFLEXIÓN</small><h2>El problema no era sólo “tener paciencia”.</h2></article></div></section>}
function Territorio(){const a=['Cuerpo y salud','Familia','Relaciones','Trabajo y vocación','Economía','Hogar','Comunidad','Interioridad'];return <section className="vx-page"><header><p>EXPLORAR · TERRITORIO</p><h1>Una vida tiene<br/>muchos lugares.</h1><span>Las Áreas no te puntúan. Son geografía para mirar dónde algo está vivo, pide cuidado o merece ser disfrutado.</span></header><div className="vx-territory">{a.map((x,i)=><button key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b><small>{i===1?'Hay un Faro vivo acá.':i===3?'Algo está tensionando otras áreas.':'Explorar sin evaluar.'}</small>→</button>)}</div></section>}
function Aprender(){return <section className="vx-page vx-learn"><header><p>APRENDER · JUNTOS</p><h1>LUMEN aprende<br/>sin apropiarse de tu vida.</h1><span>La experiencia puede mejorar el acompañamiento futuro sin convertirte en perfil ni prometer causalidades que todavía no conocemos.</span></header><div className="vx-learning"><article><small>LO QUE SABEMOS DE ESTA VIDA</small><h2>Esta práctica fue útil una vez, en este contexto.</h2><p>Eso alcanza para recordarla como recurso propio. No alcanza para afirmar que “funciona” universalmente.</p></article><article><small>CONOCIMIENTO VIVO</small><h2>La evidencia se acumula con contexto.</h2><p>Cuando una distinción demuestra cambiar pertinencia, efecto, seguridad o realizabilidad, puede ganar estructura. Antes, sigue siendo hipótesis.</p></article></div><footer><b>VIDA → LUMEN → VIDA</b><p>El objetivo no es que vuelvas más.<br/>Es acompañarte mejor cuando haga falta.</p></footer></section>}
export default function PremiumVNext(){const [scene,setScene]=useState<Scene>('inicio');const body=useMemo(()=>({inicio:<Inicio go={setScene}/>,momento:<Momento/>,mapa:<Mapa/>,faro:<Faro/>,constelacion:<Constelacion/>,vivir:<Vivir/>,retorno:<Retorno/>,santuario:<Santuario/>,territorio:<Territorio/>,aprender:<Aprender/>})[scene],[scene]);return scene==='inicio'?<Inicio go={setScene}/>:<Shell scene={scene} setScene={setScene}>{body}</Shell>}
