import {useEffect,useState} from 'react'
import {getConsentState,setConsent,type ConsentState,type ConsentScope} from '../greenfield/application/consent'
import {setMemory,setProactivity,exportSanctuary} from '../greenfield/application/embryo'
import {exportMomentOriginals,deleteMomentOriginals} from '../greenfield/application/privacy'
import {signOut} from '../greenfield/application/auth'

export function PrivacyScene({authenticated,onLogin,onChanged,onSignedOut}:{authenticated:boolean;onLogin:()=>void;onChanged:()=>Promise<void>;onSignedOut:()=>void}){
 const [state,setState]=useState<ConsentState|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[confirmDelete,setConfirmDelete]=useState(false)
 const load=()=>getConsentState().then(setState).catch(()=>setError('No pudimos cargar tus permisos.'))
 useEffect(()=>{if(authenticated)void load()},[authenticated])
 const change=async(scope:ConsentScope,enabled:boolean)=>{setBusy(true);setError('');setMessage('');try{if(scope==='memory')await setMemory(enabled);else if(scope==='proactivity')await setProactivity(enabled);else await setConsent(scope,enabled,'interface.v60.1');const next=await getConsentState();const key=scope==='memory'?'memory_allowed':scope==='proactivity'?'proactive_allowed':scope==='sharing'?'sharing_allowed':'evidence_use_allowed';if(next?.preferences[key]!==enabled)throw new Error('No pudimos verificar el permiso.');setState(next);await onChanged();setMessage(enabled?'Permiso activado.':'Permiso retirado.')}catch(e){setError(e instanceof Error?e.message:'No pudimos cambiar el permiso.')}finally{setBusy(false)}}
 const exportData=async()=>{setBusy(true);setError('');try{const [sanctuary,moments]=await Promise.all([exportSanctuary(),exportMomentOriginals()]);const blob=new Blob([JSON.stringify({sanctuary,moments},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='mi-lumen.json';link.click();URL.revokeObjectURL(url);setMessage('Tu archivo está listo.')}catch{setError('No pudimos exportar. Podés reintentar.')}finally{setBusy(false)}}
 const remove=async()=>{setBusy(true);setError('');try{await deleteMomentOriginals();const next=await exportMomentOriginals();if(next.items.length)throw new Error('No pudimos comprobar el borrado.');setMessage('Se borraron los textos originales de tus Momentos. Tu Santuario y tus Faros siguen disponibles.');setConfirmDelete(false);await onChanged()}catch{setError('No pudimos verificar el borrado.')}finally{setBusy(false)}}
 return <section className="gm-screen gm-settings"><h1>Privacidad y ritmo</h1><p>Vos elegís qué conservar y cuánto acompañamiento querés.</p>{!authenticated?<button className="gm-primary" onClick={onLogin}>Entrar para ver mis permisos</button>:<>{!state&&!error&&<p role="status">Leyendo tus preferencias…</p>}{state&&<div className="gm-permissions">{([['memory','Memoria personal','Guardar y volver a encontrar lo que elegís conservar.',state.preferences.memory_allowed],['evidence_use','Aprendizaje de LUMEN','Permitir el uso consentido de señales para mejorar el acompañamiento. No comparte tus textos originales.',state.preferences.evidence_use_allowed],['proactivity','Recordatorios','Permitir seguimientos que vos elijas. Por ahora, los ves al volver a LUMEN.',state.preferences.proactive_allowed]] as const).map(([scope,title,description,checked])=><label key={scope}><span><b>{title}</b><small>{description}</small></span><input type="checkbox" role="switch" checked={checked} disabled={busy} onChange={e=>void change(scope,e.target.checked)}/></label>)}<p>Tu ritmo: {state.preferences.proactive_allowed?'puedo ver mis seguimientos al volver':'solo cuando yo venga'}. No se envían avisos externos.</p><p>Revocar memoria detiene su uso en nuevas propuestas. Podés seguir consultando y quitando lo que decidiste guardar.</p></div>}<details><summary>Mis datos</summary>{state&&<label><input type="checkbox" checked={state.preferences.sharing_allowed} disabled={busy} onChange={e=>void change('sharing',e.target.checked)}/>Permitir que comparta recursos elegidos por mí</label>}<button disabled={busy} onClick={()=>void exportData()}>Exportar mis datos</button><button disabled={busy} onClick={()=>setConfirmDelete(true)}>Borrar textos de mis Momentos</button><p>Las notas y los recursos se quitan desde cada entrada del Santuario. Borrar textos no borra la cuenta ni el recorrido.</p>{confirmDelete&&<div role="alertdialog" aria-label="Confirmar borrado"><p>Se borran tus expresiones originales. Esta acción no se puede deshacer.</p><button disabled={busy} onClick={()=>void remove()}>Confirmar borrado de textos</button><button onClick={()=>setConfirmDelete(false)}>Cancelar</button></div>}</details><button disabled={busy} onClick={()=>void signOut().then(onSignedOut).catch(()=>setError('No pudimos cerrar tu sesión.'))}>Cerrar sesión</button></>}{busy&&<p role="status">Comprobando tu elección…</p>}{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="gm-error">{error} <button onClick={()=>void load()}>Reintentar</button></p>}</section>
}
