alter table gf_core.trajectories add column if not exists faro_history jsonb not null default '[]'::jsonb;
CREATE OR REPLACE FUNCTION gf_core.s1_interpret(p_expression text)
 RETURNS jsonb
 LANGUAGE plpgsql
 IMMUTABLE
 SET search_path TO ''
AS $function$
declare
  v text:=lower(trim(coalesce(p_expression,'')));
  v_areas text[]:='{}';
  v_caps text[]:='{}';
  v_conf numeric(4,3):=0.30;
  v_clarify boolean:=false;
  v_safety text:='clear';
  v_rule text:='open_expression';
begin
  if char_length(v)<3 or v ~ '^(no sé|no se|ni idea|qué sé yo|que se yo)[.! ]*$' then
    return jsonb_build_object('taxonomy_version','life-taxonomy.v1','area_keys','[]'::jsonb,'capacity_keys','[]'::jsonb,'confidence',0.10,'uncertainty_key','too_little_context','requires_clarification',true,'safety_state','clear','features',jsonb_build_object('ruleset','orientation.rules.v1','rule_key','too_little_context'));
  end if;
  if v ~ '(suicid|matarme|quiero morir|no quiero seguir viviendo|hacerme daño|hacerme dano|self[- ]?harm|kill myself|overdose|sobredosis|violencia grave|abuso grave)' then
    return jsonb_build_object('taxonomy_version','life-taxonomy.v1','area_keys','[]'::jsonb,'capacity_keys','[]'::jsonb,'confidence',0.95,'uncertainty_key',null,'requires_clarification',false,'safety_state','blocked','features',jsonb_build_object('ruleset','orientation.rules.v1','risk_pattern_detected',true));
  elsif v ~ '(duelo|falleci|murió|murio|muerte de|perdí a|perdi a|luto|ruptura|vacío enorme|vacio enorme)' then v_areas:=array['relationships'];v_caps:=array['integration'];v_conf:=0.88;v_rule:='grief';
  elsif v ~ '(no puedo dormir|insomnio|dormir mal|me despierto|conciliar el sueño|conciliar el sueno|sueño cortado|sueno cortado|me cuesta dormirme)' then v_areas:=array['wellbeing'];v_caps:=array['regulation'];v_conf:=0.86;v_rule:='sleep';
  elsif v ~ '(plata|dinero|deuda|finanzas|gastos|fin de mes|vencim|económic|economic|saldo)' then v_areas:=array['economy'];v_caps:=array['discernment'];v_conf:=0.85;v_rule:='economy';
  elsif v ~ '(mudanza|me mud[eé]|nuevo trabajo|cambio de vida|transición|transicion|me jubil|me recibí|me recibi|me qued[eé] sin trabajo|perdí el trabajo|perdi el trabajo)' then v_areas:=array['general_life'];v_caps:=array['adaptation'];v_conf:=0.84;v_rule:='transition';
  elsif v ~ '(cuido a|persona que cuido|cuidador|cuidadora|cuidando a|familiar enfermo|haciendo cargo de)' then v_areas:=array['family_care'];v_caps:=array['self_compassion'];v_conf:=0.83;v_rule:='caregiving';
  elsif v ~ '(poner un límite|poner un limite|decir que no|me invade|se aprovecha|no respeta|necesito un límite|necesito un limite)' then v_areas:=array['relationships'];v_caps:=array['agency'];v_conf:=0.84;v_rule:='boundaries';
  elsif v ~ '(ansiedad|ansioso|ansiosa|angustia|preocupad|nervios|miedo constante|mente no para|no dejo de imaginar|pecho apretado|cabeza acelerada|darle vueltas)' then v_areas:=array['wellbeing'];v_caps:=array['regulation'];v_conf:=0.84;v_rule:='anxiety';
  elsif v ~ '(enojad|enfadad|furios|ira|bronca|rabia|explotar|responder en caliente)' then v_areas:=array['wellbeing'];v_caps:=array['regulation'];v_conf:=0.84;v_rule:='emotion_regulation';
  elsif v ~ '(pelea|discutimos|discusión|discusion|conflicto con|reconciliar|pedir perdón|pedir perdon|disculparme|arreglar con)' then v_areas:=array['relationships'];v_caps:=array['connection'];v_conf:=0.84;v_rule:='relationship_repair';
  elsif v ~ '(me odio|soy un fracaso|culpa|vergüenza|verguenza|me castigo|no me perdono|muy duro conmigo|muy dura conmigo)' then v_areas:=array['wellbeing'];v_caps:=array['self_compassion'];v_conf:=0.82;v_rule:='self_compassion';
  elsif v ~ '(no confío en mí|no confio en mi|insegur|no soy capaz|comparándome|comparandome|autoestima|no estoy a la altura)' then v_areas:=array['general_life'];v_caps:=array['agency'];v_conf:=0.82;v_rule:='confidence';
  elsif v ~ '(hábito|habito|rutina|constancia|dejé de|deje de|retomar.*ejercicio|mantener.*costumbre)' then v_areas:=array['general_life'];v_caps:=array['agency'];v_conf:=0.80;v_rule:='habit';
  elsif v ~ '(sin energía|sin energia|sin ganas de nada|apagado|apagada|sedentario|necesito activarme|moverme un poco)' then v_areas:=array['wellbeing'];v_caps:=array['agency'];v_conf:=0.79;v_rule:='energy';
  elsif v ~ '(distraíd|distraid|no me concentro|no puedo concentrarme|pierdo el foco|mil pestañas|mil pestanas|teléfono cada|telefono cada)' then v_areas:=array['learning_growth'];v_caps:=array['attention'];v_conf:=0.80;v_rule:='focus';
  elsif v ~ '(en automático|en automatico|para qué hago todo|para que hago todo|sentido|propósito|proposito|qué importa|que importa|valores|dirección|direccion)' then v_areas:=array['meaning_spirituality'];v_caps:=array['meaning'];v_conf:=0.80;v_rule:='meaning';
  elsif v ~ '(trabajo|laburo|jefe|reuniones|burnout|agotamiento laboral|sobrecarga laboral|no desconecto|tapado de trabajo)' then v_areas:=array['work'];v_caps:=array['regulation'];v_conf:=0.80;v_rule:='work_stress';
  elsif v ~ '(no sé qué hacer|no se que hacer|no sé si|no se si|decidir|decisión|decision|confund|ordenar.*idea|claridad|qué quiero|que quiero)' then v_areas:=array['general_life'];v_caps:=array['discernment'];v_conf:=0.82;v_rule:='clarity';
  elsif v ~ '(bloquead|trabado|procrast|pateándolo|pateandolo|posterg|empezar|arrancar|primer paso|pequeño paso|pequeno paso)' then v_areas:=array['general_life'];v_caps:=array['agency'];v_conf:=0.80;v_rule:='move_forward';
  elsif v ~ '(saturad|abrumad|agotad|cansad|necesito parar|bajar un cambio|demasiado|no me entra una más|no me entra una mas)' then v_areas:=array['wellbeing'];v_caps:=array['regulation'];v_conf:=0.78;v_rule:='overload';
  elsif v ~ '(solo|sola|acompañ|acompan|hablar con alguien|necesito apoyo|conectar con alguien)' then v_areas:=array['relationships'];v_caps:=array['connection'];v_conf:=0.76;v_rule:='connection';
  elsif v ~ '(agradec|valorar|apreciar|algo bueno|reconocer lo bueno|gesto.*me hizo muy bien)' then v_areas:=array['general_life'];v_caps:=array['appreciation'];v_conf:=0.78;v_rule:='appreciation';
  else v_clarify:=true;v_conf:=0.30;v_rule:='open_expression';
  end if;
  return jsonb_build_object('understanding',case v_rule when 'grief' then 'Tal vez buscás acompañamiento para atravesar una pérdida.' when 'sleep' then 'Tal vez querés encontrar un poco de descanso.' when 'economy' then 'Tal vez necesitás ordenar una preocupación económica.' when 'transition' then 'Tal vez estás buscando cómo atravesar un cambio.' when 'caregiving' then 'Tal vez necesitás cuidarte mientras cuidás a alguien.' when 'boundaries' then 'Tal vez querés encontrar una forma de poner un límite.' when 'anxiety' then 'Tal vez querés bajar un poco el ruido de las preocupaciones.' when 'emotion_regulation' then 'Tal vez necesitás espacio antes de responder desde el enojo.' when 'relationship_repair' then 'Tal vez querés cuidar o reparar un vínculo.' when 'self_compassion' then 'Tal vez necesitás tratarte con un poco más de amabilidad.' when 'confidence' then 'Tal vez querés recuperar confianza para dar un paso.' when 'habit' then 'Tal vez querés volver a algo que te hace bien.' when 'energy' then 'Tal vez querés recuperar algo de energía.' when 'focus' then 'Tal vez buscás un poco de espacio para concentrarte.' when 'meaning' then 'Tal vez querés acercarte a lo que tiene sentido para vos.' when 'work_stress' then 'Tal vez necesitás una pausa ante lo que te exige el trabajo.' when 'clarity' then 'Tal vez buscás claridad para decidir tu próximo paso.' when 'move_forward' then 'Tal vez querés encontrar un primer paso posible.' when 'overload' then 'Tal vez necesitás bajar un cambio y recuperar espacio.' when 'connection' then 'Tal vez buscás compañía o una forma de conectar.' when 'appreciation' then 'Tal vez querés darle lugar a algo bueno que viviste.' else 'Todavía necesito un poco más de contexto para comprender qué importa ahora.' end,'taxonomy_version','life-taxonomy.v1','area_keys',to_jsonb(v_areas),'capacity_keys',to_jsonb(v_caps),'confidence',v_conf,'uncertainty_key',case when v_clarify then 'insufficient_orientation' else null end,'requires_clarification',v_clarify,'safety_state',v_safety,'features',jsonb_build_object('ruleset','orientation.rules.v1','rule_key',v_rule));
end $function$
;
CREATE OR REPLACE FUNCTION public.lumen_s1_accompany_moment(p_expression text, p_locale text, p_language text, p_surface text, p_trace_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare v_uid uuid:=auth.uid();v_person uuid;v_trace uuid:=coalesce(p_trace_id,gen_random_uuid());v_expression text:=trim(coalesce(p_expression,''));v_interp jsonb;v_moment uuid;v_episode uuid;v_run uuid;v_areas text[]:='{}';v_caps text[]:='{}';v_safety text;v_candidate_count integer:=0;v_has_applicable boolean:=false;v_coverage_state text:='unknown';v_primary jsonb;v_alt jsonb;v_rank integer:=0;v_memory boolean:=false;v_context jsonb:='{}'::jsonb;v_active_trajectory_ids jsonb:='[]'::jsonb;v_repertoire_help_ids jsonb:='[]'::jsonb;v_repertoire_available boolean:=false;r record;
begin
  if v_uid is null then raise exception 'authentication required' using errcode='28000';end if;if coalesce((auth.jwt()->>'is_anonymous')::boolean,false) then raise exception 'persistent accompaniment requires a non-anonymous account' using errcode='42501';end if;if char_length(v_expression)=0 or char_length(v_expression)>4000 then raise exception 'expression must contain 1..4000 characters' using errcode='22023';end if;
  perform set_config('app.trace_id',v_trace::text,true);perform public.lumen_bootstrap_person(v_trace);v_person:=gf_core.current_person_id();if v_person is null then raise exception 'person unavailable';end if;select coalesce(memory_allowed,false) into v_memory from gf_core.privacy_preferences where person_id=v_person;
  if v_memory then select coalesce(jsonb_agg(trajectory_id order by updated_at desc),'[]'::jsonb) into v_active_trajectory_ids from gf_core.trajectories where person_id=v_person and status='active';select coalesce(jsonb_agg(help_id order by updated_at desc),'[]'::jsonb) into v_repertoire_help_ids from gf_core.personal_repertoire where person_id=v_person and status='active';end if;
  insert into gf_core.moments(person_id,locale,language,surface,expression_length,original_retention,contract_version) values(v_person,coalesce(nullif(trim(p_locale),''),'es-AR'),coalesce(nullif(trim(p_language),''),'es'),coalesce(nullif(trim(p_surface),''),'web'),char_length(v_expression),'private_ref','s1.v49.1') returning moment_id into v_moment;
  insert into gf_private.moment_originals(moment_id,person_id,expression_text,retention_policy) values(v_moment,v_person,v_expression,'private_reclassifiable.v1') on conflict(moment_id) do update set expression_text=excluded.expression_text,retention_policy=excluded.retention_policy,updated_at=now(),revision=gf_private.moment_originals.revision+1;perform gf_private.emit_person_event('MomentOriginalPreserved','moment',v_moment,v_person,v_trace,'s1.v49.1',jsonb_build_object('original_retention','private_ref','retention_policy','private_reclassifiable.v1'));
  v_interp:=gf_core.s1_interpret(v_expression);v_safety:=v_interp->>'safety_state';v_areas:=array(select jsonb_array_elements_text(v_interp->'area_keys'));v_caps:=array(select jsonb_array_elements_text(v_interp->'capacity_keys'));v_context:=jsonb_build_object('memory_used',v_memory,'active_trajectory_ids',v_active_trajectory_ids,'repertoire_help_ids',v_repertoire_help_ids,'taxonomy_version','life-taxonomy.v1','area_keys',to_jsonb(v_areas),'capacity_keys',to_jsonb(v_caps));
  insert into gf_core.moment_interpretations(moment_id,person_id,interpreter_version,confidence,uncertainty_key,requires_clarification,safety_state,features,taxonomy_version,area_keys,capacity_keys) values(v_moment,v_person,'orientation.rules.v1',(v_interp->>'confidence')::numeric,v_interp->>'uncertainty_key',coalesce((v_interp->>'requires_clarification')::boolean,false),v_safety,coalesce(v_interp->'features','{}'::jsonb),'life-taxonomy.v1',v_areas,v_caps);
  if coalesce((v_interp->>'requires_clarification')::boolean,false) then insert into gf_core.accompaniment_episodes(person_id,moment_id,status,contract_version) values(v_person,v_moment,'clarification_needed','s1.v49.1') returning episode_id into v_episode;update gf_core.moments set status='clarification_needed' where moment_id=v_moment;return jsonb_build_object('scene_id','moment.clarify','scene_version','s1.v49.1','presence_mode','P3','episode_id',v_episode,'moment_id',v_moment,'trace_id',v_trace,'semantic_blocks',jsonb_build_array(jsonb_build_object('type','lumi_line','semantic_key','clarify.more_context')),'available_actions',jsonb_build_array(jsonb_build_object('id','tell_more','intent','continue_expression')),'safety',jsonb_build_object('state',v_safety),'coverage',jsonb_build_object('state','unknown'),'understanding',v_interp->>'understanding','interpretation',jsonb_build_object('taxonomy_version','life-taxonomy.v1','area_keys',to_jsonb(v_areas),'capacity_keys',to_jsonb(v_caps),'confidence',v_interp->'confidence','uncertainty_key',v_interp->'uncertainty_key'),'privacy',jsonb_build_object('original_retention','private_ref','retention_policy','private_reclassifiable.v1','shared_learning',false));end if;
  insert into gf_core.accompaniment_episodes(person_id,moment_id,status,contract_version) values(v_person,v_moment,case when v_safety='blocked' then 'no_match' else 'proposed' end,'s1.v49.1') returning episode_id into v_episode;
  if v_safety='blocked' then insert into gf_core.no_match_events(episode_id,person_id,reason_code,coverage_state,coverage_gap) values(v_episode,v_person,'safety_scope','restricted',false);update gf_core.moments set status='decided' where moment_id=v_moment;return jsonb_build_object('scene_id','moment.safety_referral','scene_version','s1.v49.1','presence_mode','P4','episode_id',v_episode,'moment_id',v_moment,'trace_id',v_trace,'semantic_blocks',jsonb_build_array(jsonb_build_object('type','safety_referral','semantic_key','safety.human_help_now')),'available_actions',jsonb_build_array(jsonb_build_object('id','seek_human_help','intent','seek_human_help'),jsonb_build_object('id','close','intent','close')),'safety',jsonb_build_object('state','blocked'),'coverage',jsonb_build_object('state','restricted','reason','safety_scope'),'privacy',jsonb_build_object('original_retention','private_ref','retention_policy','private_reclassifiable.v1','shared_learning',false));end if;
  select count(distinct hp.help_id),coalesce(bool_or(ha.state='applicable'),false) into v_candidate_count,v_has_applicable from gf_core.help_applicability ha join gf_core.help_versions hv on hv.help_version_id=ha.help_version_id join gf_core.help_possibilities hp on hp.help_id=hv.help_id and hp.current_version=hv.version where hp.lifecycle in('active_limited','active') and ha.state in('applicable','partial') and ha.taxonomy_version='life-taxonomy.v1' and ha.area_key=any(v_areas) and ha.capacity_key=any(v_caps);v_coverage_state:=case when v_candidate_count=0 then 'not_covered' when v_has_applicable then 'covered' else 'partial' end;
  if v_candidate_count=0 then insert into gf_core.no_match_events(episode_id,person_id,reason_code,coverage_state,coverage_gap) values(v_episode,v_person,'no_sufficient_applicability',v_coverage_state,true);update gf_core.accompaniment_episodes set status='no_match',completed_at=now() where episode_id=v_episode;update gf_core.moments set status='decided' where moment_id=v_moment;return jsonb_build_object('scene_id','moment.no_match','scene_version','s1.v49.1','presence_mode','P2','episode_id',v_episode,'moment_id',v_moment,'trace_id',v_trace,'semantic_blocks',jsonb_build_array(jsonb_build_object('type','lumi_line','semantic_key','no_match.honest')),'available_actions',jsonb_build_array(jsonb_build_object('id','rephrase','intent','rephrase'),jsonb_build_object('id','close','intent','close')),'safety',jsonb_build_object('state','clear'),'coverage',jsonb_build_object('state',v_coverage_state,'reason','no_sufficient_applicability'),'understanding',v_interp->>'understanding','interpretation',jsonb_build_object('taxonomy_version','life-taxonomy.v1','area_keys',to_jsonb(v_areas),'capacity_keys',to_jsonb(v_caps),'confidence',v_interp->'confidence'),'privacy',jsonb_build_object('original_retention','private_ref','retention_policy','private_reclassifiable.v1','shared_learning',false));end if;
  if v_memory then select exists(select 1 from gf_core.personal_repertoire pr join gf_core.help_possibilities hp on hp.help_id=pr.help_id join gf_core.help_versions hv on hv.help_id=hp.help_id and hv.version=hp.current_version join gf_core.help_applicability ha on ha.help_version_id=hv.help_version_id where pr.person_id=v_person and pr.status='active' and hp.lifecycle in('active_limited','active') and ha.state in('applicable','partial') and ha.taxonomy_version='life-taxonomy.v1' and ha.area_key=any(v_areas) and ha.capacity_key=any(v_caps)) into v_repertoire_available;end if;
  insert into gf_core.decision_runs(episode_id,person_id,policy_version,interpreter_version,coverage_version,safety_state,coverage_state,eligible_count,decision_reason_key,continuity_context) values(v_episode,v_person,'decision.v49.1','orientation.rules.v1','coverage.eval.v1',v_safety,v_coverage_state,v_candidate_count,case when v_repertoire_available then 'relevant_repertoire_available' else 'area_capacity_applicability_match' end,v_context) returning decision_run_id into v_run;
  for r in with eligible as(select hp.help_id,hv.help_version_id,hp.help_type,hp.canonical_code,hl.title,hl.summary,hl.content_payload,hv.duration_minutes,hv.energy,hv.detail,bool_or(ha.state='applicable') as strong_match,count(*) as match_count,max(ha.applicability_confidence) as applicability_confidence,min(ha.priority_hint) as priority_hint,case when v_memory and exists(select 1 from gf_core.personal_repertoire pr where pr.person_id=v_person and pr.help_id=hp.help_id and pr.status='active') then 0 else 1 end as repertoire_rank from gf_core.help_applicability ha join gf_core.help_versions hv on hv.help_version_id=ha.help_version_id join gf_core.help_possibilities hp on hp.help_id=hv.help_id and hp.current_version=hv.version join lateral(select hloc.* from gf_core.help_localizations hloc where hloc.help_version_id=hv.help_version_id order by case when hloc.locale=coalesce(nullif(trim(p_locale),''),'es-AR') then 0 when left(hloc.locale,2)=left(coalesce(nullif(trim(p_language),''),'es'),2) then 1 when hloc.locale='es-AR' then 2 else 3 end limit 1) hl on true where hp.lifecycle in('active_limited','active') and ha.state in('applicable','partial') and ha.taxonomy_version='life-taxonomy.v1' and ha.area_key=any(v_areas) and ha.capacity_key=any(v_caps) group by hp.help_id,hv.help_version_id,hp.help_type,hp.canonical_code,hl.title,hl.summary,hl.content_payload,hv.duration_minutes,hv.energy,hv.detail) select * from eligible order by strong_match desc,match_count desc,applicability_confidence desc,repertoire_rank,priority_hint,canonical_code limit 2 loop v_rank:=v_rank+1;insert into gf_core.decision_candidates(decision_run_id,person_id,help_id,help_version_id,eligibility_status,reason_key,priority_hint) values(v_run,v_person,r.help_id,r.help_version_id,'eligible',case when r.repertoire_rank=0 then 'relevant_own_repertoire' else 'area_capacity_applicability' end,r.priority_hint);insert into gf_core.candidate_exposures(decision_run_id,person_id,help_id,help_version_id,display_rank) values(v_run,v_person,r.help_id,r.help_version_id,v_rank);if v_rank=1 then v_primary:=jsonb_build_object('help_id',r.help_id,'help_version_id',r.help_version_id,'help_type',r.help_type,'title',r.title,'summary',r.summary,'content',r.content_payload,'duration_minutes',r.duration_minutes,'energy',r.energy,'detail',r.detail,'from_own_repertoire',r.repertoire_rank=0,'applicability_confidence',r.applicability_confidence);else v_alt:=jsonb_build_object('help_id',r.help_id,'help_version_id',r.help_version_id,'help_type',r.help_type,'title',r.title,'summary',r.summary,'content',r.content_payload,'duration_minutes',r.duration_minutes,'energy',r.energy,'detail',r.detail,'from_own_repertoire',r.repertoire_rank=0,'applicability_confidence',r.applicability_confidence);end if;end loop;
  update gf_core.moments set status='decided' where moment_id=v_moment;return jsonb_build_object('scene_id','moment.help','scene_version','s1.v49.1','presence_mode','P2','episode_id',v_episode,'moment_id',v_moment,'decision_run_id',v_run,'trace_id',v_trace,'semantic_blocks',jsonb_build_array(jsonb_build_object('type','lumi_line','semantic_key','help.offer_humble'),jsonb_build_object('type','help_preview','primary',v_primary,'alternative',v_alt),jsonb_build_object('type','continuity_hint','semantic_key',case when coalesce((v_primary->>'from_own_repertoire')::boolean,false) then 'continuity.own_repertoire' else 'continuity.none' end)),'available_actions',jsonb_build_array(jsonb_build_object('id','try_primary','intent','select_help','payload',jsonb_build_object('help_id',v_primary->>'help_id')),jsonb_build_object('id','not_this','intent','reject_help')),'safety',jsonb_build_object('state','clear'),'coverage',jsonb_build_object('state',v_coverage_state),'understanding',v_interp->>'understanding','interpretation',jsonb_build_object('taxonomy_version','life-taxonomy.v1','area_keys',to_jsonb(v_areas),'capacity_keys',to_jsonb(v_caps),'confidence',v_interp->'confidence','uncertainty_key',v_interp->'uncertainty_key'),'continuity',jsonb_build_object('memory_used',v_memory,'own_repertoire_reused',coalesce((v_primary->>'from_own_repertoire')::boolean,false),'active_trajectory_count',jsonb_array_length(v_active_trajectory_ids)),'delivery',jsonb_build_object('pattern','prepare_possibility_integrate','optional',true,'prepare_semantic_key','help.offer_humble','integrate_semantic_key','outcome.thank_and_release'),'privacy',jsonb_build_object('original_retention','private_ref','retention_policy','private_reclassifiable.v1','shared_learning',false));
end $function$
;
CREATE OR REPLACE FUNCTION public.lumen_s5_share_help(p_space_id uuid, p_help_id uuid, p_trace_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$ declare v_uid uuid:=auth.uid();v_person uuid;v_contribution uuid;v_trace uuid:=coalesce(p_trace_id,gen_random_uuid()); begin
 if v_uid is null then raise exception 'authentication required'; end if;
 select person_id into v_person from gf_core.persons where auth_user_id=v_uid;
 if not exists(select 1 from gf_core.privacy_preferences where person_id=v_person and sharing_allowed) then raise exception 'sharing consent required' using errcode='42501'; end if;
 if not exists(select 1 from gf_core.memberships where space_id=p_space_id and person_id=v_person and status='active') then raise exception 'active membership required' using errcode='42501'; end if;
 if not exists(select 1 from gf_core.help_possibilities where help_id=p_help_id and lifecycle in('active_limited','active')) then raise exception 'help unavailable'; end if;
 insert into gf_core.contributions(space_id,person_id,help_id) values(p_space_id,v_person,p_help_id) returning contribution_id into v_contribution;
 perform gf_private.emit_person_event('TissueContributionShared','contribution',v_contribution,v_person,v_trace,'s5.v1',jsonb_build_object('space_id',p_space_id,'help_id',p_help_id));
 return jsonb_build_object('contribution_id',v_contribution,'space_id',p_space_id,'help_id',p_help_id,'trace_id',v_trace);
end $function$
;
CREATE OR REPLACE FUNCTION public.lumen_s2_update_trajectory(p_trajectory_id uuid, p_faro_text text, p_status text, p_trace_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$ declare v_uid uuid:=auth.uid();v_person uuid;v_trace uuid:=coalesce(p_trace_id,gen_random_uuid());v_faro text:=trim(coalesce(p_faro_text,''));v_status text:=lower(trim(coalesce(p_status,'')));v_event text; begin
 if v_uid is null then raise exception 'authentication required' using errcode='28000'; end if;
 select person_id into v_person from gf_core.persons where auth_user_id=v_uid;
 if char_length(v_faro) not between 1 and 280 or v_status not in('active','paused','closed') then raise exception 'invalid trajectory' using errcode='22023'; end if;
 update gf_core.trajectories set faro_history=case when faro_text<>v_faro then faro_history||jsonb_build_array(jsonb_build_object('text',faro_text,'until',now())) else faro_history end,faro_text=v_faro,status=v_status,updated_at=now(),revision=revision+1 where trajectory_id=p_trajectory_id and person_id=v_person;
 if not found then raise exception 'trajectory not found' using errcode='P0002'; end if;
 v_event:=case when v_status='paused' then 'TrajectoryPaused' else 'TrajectoryChanged' end;
 perform gf_private.emit_person_event(v_event,'trajectory',p_trajectory_id,v_person,v_trace,'s2.v1',jsonb_build_object('status',v_status));
 return jsonb_build_object('trajectory_id',p_trajectory_id,'faro_text',v_faro,'status',v_status,'trace_id',v_trace);
end $function$
;
CREATE OR REPLACE FUNCTION public.lumen_s2_snapshot()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare v_uid uuid:=auth.uid();v_person uuid;v_memory boolean:=false;v_trajectories jsonb;v_repertoire jsonb;v_sanctuary_count integer;begin
 if v_uid is null then raise exception 'authentication required' using errcode='28000';end if;
 select person_id into v_person from gf_core.persons where auth_user_id=v_uid;
 if v_person is null then return jsonb_build_object('memory_allowed',false,'trajectories','[]'::jsonb,'repertoire','[]'::jsonb,'sanctuary_count',0);end if;
 select coalesce(memory_allowed,false) into v_memory from gf_core.privacy_preferences where person_id=v_person;
 select coalesce(jsonb_agg(jsonb_build_object(
   'trajectory_id',t.trajectory_id,'faro_text',t.faro_text,'history',t.faro_history,'status',t.status,'capability_keys',to_jsonb(t.capability_keys),'origin_moment_id',t.origin_moment_id,
   'path',coalesce((select jsonb_agg(jsonb_build_object('path_item_id',pi.path_item_id,'help_id',pi.help_id,'label',pi.label,'position',pi.position,'status',pi.status,'cultivation_move',pi.cultivation_move,'source_kind',pi.source_kind,'source_ref_id',pi.source_ref_id) order by pi.position) from gf_core.path_items pi join gf_core.paths p on p.path_id=pi.path_id where p.trajectory_id=t.trajectory_id),'[]'::jsonb)
 ) order by t.updated_at desc),'[]'::jsonb) into v_trajectories from gf_core.trajectories t where t.person_id=v_person;
 select coalesce(jsonb_agg(jsonb_build_object('repertoire_id',r.repertoire_id,'help_id',r.help_id,'title',hl.title,'summary',hl.summary,'times_reused',r.times_reused,'last_used_at',r.last_used_at,'capability_keys',to_jsonb(r.capability_keys),'user_confirmed',r.user_confirmed) order by r.updated_at desc),'[]'::jsonb) into v_repertoire from gf_core.personal_repertoire r join gf_core.help_possibilities hp on hp.help_id=r.help_id join gf_core.help_versions hv on hv.help_id=hp.help_id and hv.version=hp.current_version join lateral(select title,summary from gf_core.help_localizations where help_version_id=hv.help_version_id order by case when locale='es-AR' then 0 else 1 end limit 1) hl on true where r.person_id=v_person and r.status='active';
 select count(*) into v_sanctuary_count from gf_private.sanctuary_entries where person_id=v_person;
 return jsonb_build_object('memory_allowed',coalesce(v_memory,false),'trajectories',v_trajectories,'repertoire',v_repertoire,'sanctuary_count',v_sanctuary_count);
end $function$
;
