insert into gf_core.providers(provider_code,display_name,provider_kind,provenance,rights)
values ('va_lumen_flagship','VA+LUMEN · Colección insignia','internal_curated',jsonb_build_object('source','A62 world-class pre-Pauli','version','flagship.v1'),jsonb_build_object('use','internal_original','redistribution','allowed'))
on conflict(provider_code) do nothing;

create temporary table a62_seed(
  code text, help_type text, mechanism text, title text, summary text, content jsonb,
  duration int, energy text, area_key text, capacity_key text, roles text[], priority smallint
) on commit drop;

insert into a62_seed values
('flagship_breathe_arrive','practice','regulation_breath','Llegar al cuerpo','Una respiración breve para bajar intensidad sin exigir que nada desaparezca.',jsonb_build_object('intro','No hace falta calmarte perfecto. Sólo darle al cuerpo una señal de un poco más de espacio.','steps',jsonb_build_array('Aflojá apenas la mandíbula y los hombros.','Inhalá cómodo por la nariz. Exhalá un poco más lento, sin contar si no querés.','Repetí cinco veces y notá si apareció aunque sea un 5% más de espacio.','Antes de seguir, preguntate: ¿qué necesita menos urgencia ahora?')),4,'very_low','wellbeing','regulation',array['PRACTICE','APPLY','SUSTAIN'],10),
('flagship_ground_present','practice','sensory_grounding','Volver a este lugar','Un anclaje sensorial para cuando la cabeza se va demasiado lejos.',jsonb_build_object('intro','No vamos a discutir con tus pensamientos. Vamos a darle más realidad al presente.','steps',jsonb_build_array('Mirá alrededor y encontrá tres formas o colores concretos.','Sentí dos puntos de apoyo de tu cuerpo.','Escuchá un sonido cercano y otro más lejano.','Elegí una acción pequeña que pertenezca a los próximos diez minutos.')),5,'very_low','general_life','regulation',array['PRACTICE','APPLY','VARY'],12),
('flagship_values_compass','reflection','values_discernment','La pregunta que ordena','Una pausa para separar urgencia, expectativa y aquello que de verdad querés cuidar.',jsonb_build_object('intro','A veces decidir mejor empieza por distinguir lo importante de lo ruidoso.','prompts',jsonb_build_array('¿Qué parte de esto es realmente importante para vos?','¿Qué estás intentando proteger, cuidar o construir?','Si mañana miraras esta decisión con respeto por vos mismo, ¿qué te gustaría haber honrado?')),7,'low','general_life','discernment',array['UNDERSTAND','REFLECT','INTEGRATE'],10),
('flagship_two_chairs','reflection','perspective_shift','Dos voces, una decisión','Escuchar la parte que quiere avanzar y la parte que quiere protegerte.',jsonb_build_object('intro','No hace falta elegir una voz como la correcta. Las dos suelen estar cuidando algo.','prompts',jsonb_build_array('La parte que quiere avanzar diría…','La parte que duda o teme diría…','¿Qué necesidad legítima tiene cada una?','¿Qué decisión pequeña podría respetar a ambas lo suficiente?')),8,'low','learning_growth','discernment',array['REFLECT','INTEGRATE','VARY'],18),
('flagship_tiny_courage','human_action','agency_micro_action','Un gesto de coraje suficientemente pequeño','Mover algo importante sin esperar a sentirte completamente listo.',jsonb_build_object('intro','El objetivo no es vencer el miedo. Es reducir el tamaño del primer movimiento.','steps',jsonb_build_array('Nombrá una acción que venís evitando.','Reducila hasta que pueda hacerse en menos de cinco minutos.','Hacé sólo el primer movimiento visible.','Después decidí de nuevo, sin obligación de continuar.')),5,'low','general_life','agency',array['PRACTICE','APPLY','SUSTAIN'],10),
('flagship_kind_inner_voice','practice','self_compassion','Hablarte como alguien de tu lado','Cambiar el tono interno sin negar responsabilidad ni dificultad.',jsonb_build_object('intro','Autocompasión no es darte la razón en todo. Es dejar de lastimarte mientras intentás responder mejor.','steps',jsonb_build_array('Nombrá en una frase qué está siendo difícil.','Decí: esto es humano; no soy la única persona que podría sentirse así.','Preguntate: ¿qué tono me ayudaría a responder mejor, no peor?','Decite una frase breve en ese tono.')),6,'very_low','wellbeing','self_compassion',array['PRACTICE','REFLECT','INTEGRATE'],10),
('flagship_listen_deeper','conversation','relational_listening','Escuchar sin preparar la defensa','Una conversación para recuperar conexión antes de intentar tener razón.',jsonb_build_object('intro','Probá entrar a la conversación con una sola intención: entender un poco mejor.','steps',jsonb_build_array('Preguntá: ¿qué es lo más importante que querés que entienda?','No interrumpas durante un minuto, salvo para aclarar.','Devolvé lo que entendiste sin argumentar.','Recién después contá tu mirada en primera persona.')),10,'medium','relationships','connection',array['PRACTICE','APPLY','CONNECT'],10),
('flagship_repair_bridge','conversation','relational_repair','Abrir una puerta de reparación','Una estructura simple para acercarte después de una fricción.',jsonb_build_object('intro','Reparar no exige resolver toda la relación en una charla. A veces alcanza con abrir una puerta honesta.','steps',jsonb_build_array('Nombrá tu parte sin agregar un “pero”.','Reconocé el impacto que pudo haber tenido.','Decí qué te gustaría hacer diferente.','Preguntá si la otra persona quiere contarte cómo lo vivió.')),9,'medium','relationships','connection',array['APPLY','CONNECT','INTEGRATE'],15),
('flagship_body_reset','practice','movement_reset','Mover para destrabar','Una secuencia corporal breve para salir de la inmovilidad mental.',jsonb_build_object('intro','No hace falta entrenar. Sólo cambiar un poco el estado del cuerpo.','steps',jsonb_build_array('Ponete de pie si te resulta posible.','Mové hombros y brazos suavemente durante treinta segundos.','Caminá o desplazate durante dos minutos prestando atención a las plantas de los pies.','Al terminar, elegí una sola cosa a la que volver.')),5,'medium','wellbeing','attention',array['PRACTICE','APPLY','VARY'],18),
('flagship_evening_integration','reflection','daily_integration','Cerrar el día sin evaluarte','Un cierre breve para convertir experiencia en aprendizaje, no en puntaje.',jsonb_build_object('intro','No es un examen del día. Es una forma de dejar que algo de lo vivido quede con vos.','prompts',jsonb_build_array('¿Qué momento del día merece ser reconocido?','¿Qué fue difícil y qué te mostró de vos o de lo que necesitás?','¿Qué te gustaría llevar mañana, y qué podés dejar acá?')),7,'very_low','general_life','integration',array['REFLECT','INTEGRATE','SUSTAIN'],10),
('flagship_meaning_thread','reflection','meaning_thread','Encontrar un hilo de sentido','Reconocer aquello que sigue importando incluso en etapas inciertas.',jsonb_build_object('intro','Sentido no siempre es una gran respuesta. A veces es un hilo suficientemente vivo para hoy.','prompts',jsonb_build_array('¿Qué persona, tarea, valor o posibilidad sigue llamándote un poco?','¿Qué gesto pequeño expresaría eso esta semana?','¿Qué parte depende de vos y qué parte conviene soltar?')),8,'low','meaning_spirituality','meaning',array['UNDERSTAND','REFLECT','APPLY','INTEGRATE'],12),
('flagship_adapt_next_version','tool','adaptive_reframe','Probar otra versión','Cuando algo útil dejó de encajar, conservar el principio y cambiar la forma.',jsonb_build_object('intro','Que una práctica no funcione igual no significa que hayas retrocedido. Puede pedir otra forma.','steps',jsonb_build_array('Nombrá qué parte de lo que hacías sí ayudaba.','Identificá qué dejó de encajar: tiempo, energía, contexto o necesidad.','Diseñá una versión más pequeña o diferente para este momento.','Probala una vez y volvé a mirar, sin convertirla en obligación.')),8,'low','learning_growth','adaptation',array['VARY','APPLY','REFLECT','INTEGRATE'],10);

insert into gf_core.help_possibilities(canonical_code,help_type,provider_id,lifecycle,risk_class,evidence_class)
select s.code,s.help_type,p.provider_id,'active_limited','low','practice_based'
from a62_seed s cross join gf_core.providers p
where p.provider_code='va_lumen_flagship'
on conflict(canonical_code) do nothing;

insert into gf_core.help_versions(help_id,version,mechanism_key,detail,duration_minutes,energy,accessibility)
select hp.help_id,1,s.mechanism,jsonb_build_object('delivery','native','collection','flagship.v1','experience_quality','immersive'),s.duration,s.energy,
       jsonb_build_object('screen_reader',true,'reduced_motion',true,'low_energy',s.energy in ('very_low','low'))
from a62_seed s join gf_core.help_possibilities hp on hp.canonical_code=s.code
where not exists(select 1 from gf_core.help_versions hv where hv.help_id=hp.help_id and hv.version=1);

insert into gf_core.help_localizations(help_version_id,locale,title,summary,content_payload,cultural_scope,provenance)
select hv.help_version_id,'es-AR',s.title,s.summary,s.content,array['es-AR','latam'],jsonb_build_object('author','VA+LUMEN','collection','flagship.v1','act','A62')
from a62_seed s join gf_core.help_possibilities hp on hp.canonical_code=s.code join gf_core.help_versions hv on hv.help_id=hp.help_id and hv.version=1
on conflict(help_version_id,locale) do update set title=excluded.title,summary=excluded.summary,content_payload=excluded.content_payload,provenance=excluded.provenance;

insert into gf_core.help_applicability(help_version_id,taxonomy_version,area_key,capacity_key,state,priority_hint,applicability_confidence,evidence_count,provenance,cultivation_roles,cultivation_vocab_version)
select hv.help_version_id,'life-taxonomy.v1',s.area_key,s.capacity_key,'applicable',s.priority,0.82,0,
       jsonb_build_object('source','A62 editorial curation','collection','flagship.v1'),s.roles,'cultivation.v1'
from a62_seed s join gf_core.help_possibilities hp on hp.canonical_code=s.code join gf_core.help_versions hv on hv.help_id=hp.help_id and hv.version=1
on conflict(help_version_id,taxonomy_version,area_key,capacity_key) do update set state='applicable',priority_hint=excluded.priority_hint,applicability_confidence=excluded.applicability_confidence,provenance=excluded.provenance,cultivation_roles=excluded.cultivation_roles,cultivation_vocab_version=excluded.cultivation_vocab_version,updated_at=now();